"""Besin kataloğu isim düzeltmeleri (2026-09-27 denetimi).

USDA kökenli kayıtların Türkçe adları LLM ile toplu çevrildi (translate_catalog.py)
ve çeviri önbelleği git dışında (data_sources/usda/). Denetimde bulunanlar:
- fdc 2709136..2709195 bloğunda her çeviri BİR SONRAKİ öğeye aitti (ör.
  "Lime juice" -> "%100 portakal suyu"); kalori değerleri İngilizce ada ait olduğu
  için kullanıcı portakal suyu deyince misket limonu suyunun değerini alıyordu.
- yanlış çeviriler (Prunes -> "Gün kurusu kayısı", Swiss chard -> "Ispanak",
  Sausage -> "Salam", Popcorn -> "Mısır patlağı", Cowpeas -> "Soya fasulyesi"...),
  uydurma kelimeler ("Kızılçibör", "Sparoz", "Erişme") ve isim yerine çeviri prompt'u.

seed_catalogs.py seed'den sonra bunları uygular; mevcut DB için:
    python -m scripts.food_catalog_fixes
"""

from app.db.session import SessionLocal
from app.models.food_catalog import FoodCatalog
from app.services import food_catalog_service

# fdc_id -> doğru name_tr
NAME_FIXES: dict[int, str] = {
    167568: 'Pastacılık çikolatası, şekersiz, kareler',  # Baking chocolate, unsweetened, squares (kural: yanlış çeviri/yazım)
    167761: 'Graviola (soursop), çiğ',  # Soursop, raw (yanlış çeviri)
    167803: 'Kızılcık sosu, bütün taneli, konserve, OCEAN SPRAY',  # Cranberry sauce, whole, canned, OCEAN SPRAY (yazım/uydurma kelime)
    167804: 'Kızılcık sosu, jöleli, konserve, OCEAN SPRAY',  # Cranberry sauce, jellied, canned, OCEAN SPRAY (yazım/uydurma kelime)
    168092: 'Hindi jambonu, dilimlenmiş, ekstra yağsız, paketli veya şarküteri',  # Ham, turkey, sliced, extra lean, prepackaged or deli (yanlış çeviri)
    168159: 'Kuru erik, konserve, yoğun şuruplu, katı ve sıvı kısımları dahil',  # Prunes, canned, heavy syrup pack, solids and liquids (yanlış çeviri)
    168160: 'Kuru erik, kurutulmuş (düşük nemli), pişmemiş',  # Prunes, dehydrated (low-moisture), uncooked (yanlış çeviri)
    168161: 'Kuru erik, kurutulmuş (düşük nemli), pişmiş',  # Prunes, dehydrated (low-moisture), stewed (yanlış çeviri)
    168391: 'Kudret narı (acı kavun), yapraklı uçlar, çiğ',  # Balsam-pear (bitter gourd), leafy tips, raw (kural: yanlış çeviri/yazım)
    168393: 'Kudret narı (acı kavun), meyve, çiğ',  # Balsam-pear (bitter gourd), pods, raw (kural: yanlış çeviri/yazım)
    168394: 'Kudret narı (acı kavun), meyve, pişmiş, haşlanmış, süzülmüş, tuzsuz',  # Balsam-pear (bitter gourd), pods, cooked, boiled, drained, w (kural: yanlış çeviri/yazım)
    168402: 'Börülce (siyah gözlü), olgunlaşmamış tohumlar, pişmiş, haşlanmış, süzülmüş, tuzsuz',  # Cowpeas (blackeyes), immature seeds, cooked, boiled, drained (kural: yanlış çeviri/yazım)
    168403: 'Börülce (siyah gözlü), olgunlaşmamış tohumlar, dondurulmuş, hazırlanmamış',  # Cowpeas (blackeyes), immature seeds, frozen, unprepared (kural: yanlış çeviri/yazım)
    168405: 'Börülce, tohumlu genç kapsüller, çiğ',  # Cowpeas, young pods with seeds, raw (kural: yanlış çeviri/yazım)
    168406: 'Börülce, yapraklı uçlar, pişmiş, haşlanmış, süzülmüş, tuzsuz',  # Cowpeas, leafy tips, cooked, boiled, drained, without salt (kural: yanlış çeviri/yazım)
    168495: 'Kudret narı (acı kavun), yapraklı uçlar, pişmiş, haşlanmış, süzülmüş, tuzlu',  # Balsam-pear (bitter gourd), leafy tips, cooked, boiled, drai (kural: yanlış çeviri/yazım)
    168496: 'Kudret narı (acı kavun), meyve, pişmiş, haşlanmış, süzülmüş, tuzlu',  # Balsam-pear (bitter gourd), pods, cooked, boiled, drained, w (kural: yanlış çeviri/yazım)
    168526: 'Börülce (siyah gözlü), olgunlaşmamış tohumlar, pişmiş, haşlanmış, süzülmüş, tuzlu',  # Cowpeas (blackeyes), immature seeds, cooked, boiled, drained (kural: yanlış çeviri/yazım)
    168527: 'Börülce (siyah gözlü), olgunlaşmamış tohumlar, dondurulmuş, pişmiş, haşlanmış, süzülmüş, tuzlu',  # Cowpeas (blackeyes), immature seeds, frozen, cooked, boiled, (kural: yanlış çeviri/yazım)
    168528: 'Börülce, tohumlu genç kapsüller, pişmiş, haşlanmış, süzülmüş, tuzlu',  # Cowpeas, young pods with seeds, cooked, boiled, drained, wit (kural: yanlış çeviri/yazım)
    168529: 'Börülce, yapraklı uçlar, pişmiş, haşlanmış, süzülmüş, tuzlu',  # Cowpeas, leafy tips, cooked, boiled, drained, with salt (kural: yanlış çeviri/yazım)
    168859: 'Tortilla cipsi, düşük yağlı, yağsız fırınlanmış',  # Tortilla chips, low fat, baked without fat (yazım/uydurma kelime)
    168860: 'Peynirli mısır çerezi (puf ve burgu), fırınlanmış, düşük yağlı',  # Cheese puffs and twists, corn based, baked, low fat (yanlış çeviri)
    169220: 'Börülce (siyah gözlü), olgunlaşmamış tohumlar, çiğ',  # Cowpeas (blackeyes), immature seeds, raw (kural: yanlış çeviri/yazım)
    169224: 'Börülce, yapraklı uçlar, çiğ',  # Cowpeas, leafy tips, raw (kural: yanlış çeviri/yazım)
    169279: 'Lahana turşusu (sauerkraut), konserve, katı ve sıvı kısımları dahil',  # Sauerkraut, canned, solids and liquids (yazım/uydurma kelime)
    169343: 'Pazı, pişmiş, haşlanmış, süzülmüş, tuzlu',  # Chard, swiss, cooked, boiled, drained, with salt (kural: yanlış çeviri/yazım)
    169991: 'Pazı, çiğ',  # Chard, swiss, raw (kural: yanlış çeviri/yazım)
    169994: 'Frenk soğanı, çiğ',  # Chives, raw (yanlış çeviri)
    170009: 'Yaban havucu (parsnip), pişmiş, haşlanmış, süzülmüş, tuzsuz',  # Parsnips, cooked, boiled, drained, without salt (kural: yanlış çeviri/yazım)
    170075: 'Frenk soğanı, dondurularak kurutulmuş',  # Chives, freeze-dried (yanlış çeviri)
    170197: 'Dana eti, salamura edilmiş, kahvaltılık şeritler, çiğ veya ısıtılmamış',  # Beef, cured, breakfast strips, raw or unheated (yanlış çeviri)
    170198: 'Dana eti, salamura edilmiş, kahvaltılık şeritler, pişmiş',  # Beef, cured, breakfast strips, cooked (yanlış çeviri)
    170401: 'Pazı, pişmiş, haşlanmış, süzülmüş, tuzsuz',  # Chard, swiss, cooked, boiled, drained, without salt (kural: yanlış çeviri/yazım)
    170417: 'Yaban havucu (parsnip), çiğ',  # Parsnips, raw (kural: yanlış çeviri/yazım)
    170486: 'Maydanoz, dondurularak kurutulmuş',  # Parsley, freeze-dried (yazım/uydurma kelime)
    170508: 'Yaban havucu (parsnip), pişmiş, haşlanmış, süzülmüş, tuzlu',  # Parsnips, cooked, boiled, drained, with salt (kural: yanlış çeviri/yazım)
    171183: 'SMART SOUP, Tay usulü Hindistan cevizli köri çorbası',  # SMART SOUP, Thai Coconut Curry (yanlış çeviri)
    171601: 'Barbekü soslu et somunu, domuz, sığır',  # Barbecue loaf, pork, beef (yanlış çeviri)
    171704: 'Kayısı nektarı, konserve, ilave askorbik asitli',  # Apricot nectar, canned, with added ascorbic acid (yanlış çeviri)
    171833: 'Sos, yaban turpu (horseradish)',  # Sauce, horseradish (yanlış çeviri)
    171904: 'Kızılcık suyu kokteyli, şişelenmiş, düşük kalorili, kalsiyumlu, sakarinli ve mısır tatlandırıcılı',  # Cranberry juice cocktail, bottled, low calorie, with calcium (yazım/uydurma kelime)
    172023: 'Darı unu',  # Millet flour (yanlış çeviri)
    172334: 'Katılaştırılmış yağ (Shortening), şekerleme, fraksiyonel palmiye',  # Shortening, confectionery, fractionated palm (yazım/uydurma kelime)
    172416: 'Beç tavuğu (guinea hen), et ve deri, çiğ',  # Guinea hen, meat and skin, raw (yanlış çeviri)
    172425: 'Moth fasulyesi, olgun tohumlar, çiğ',  # Mothbeans, mature seeds, raw (kural: yanlış çeviri/yazım)
    172426: 'Moth fasulyesi, olgun tohumlar, pişmiş, haşlanmış, tuzsuz',  # Mothbeans, mature seeds, cooked, boiled, without salt (kural: yanlış çeviri/yazım)
    172686: 'Ekmek, buğday',  # Bread, wheat (yazım/uydurma kelime)
    172786: 'Turta, pekan cevizli, tariften hazırlanmış',  # Pie, pecan, prepared from recipe (yanlış çeviri)
    172926: 'Zeytinli et somunu, domuz',  # Olive loaf, pork (yanlış çeviri)
    173161: 'Pirinç krakeri',  # Rice crackers (yanlış çeviri)
    173257: 'Mckee Baking, Little Debbie Nutty Bars, Yer Fıstığı Ezmeli Gofretler, Çikolata Kaplı',  # Mckee Baking, Little Debbie Nutty Bars, Wafers with Peanut B (yanlış çeviri)
    173472: 'Yaban turpu, hazırlanmış',  # Horseradish, prepared (yanlış çeviri)
    173758: 'Börülce, yaygın (blackeyes, crowder, southern), olgun tohumlar, çiğ',  # Cowpeas, common (blackeyes, crowder, southern), mature seeds (kural: yanlış çeviri/yazım)
    173760: 'Börülce, yaygın (blackeyes, crowder, southern), olgun tohumlar, konserve, sade',  # Cowpeas, common (blackeyes, crowder, southern), mature seeds (kural: yanlış çeviri/yazım)
    173805: 'Moth fasulyesi, olgun tohumlar, pişmiş, haşlanmış, tuzlu',  # Mothbeans, mature seeds, cooked, boiled, with salt (kural: yanlış çeviri/yazım)
    173961: 'Kızılcık sosu, konserve, tatlandırılmış',  # Cranberry sauce, canned, sweetened (yazım/uydurma kelime)
    173962: 'Kızılcık-portakal sosu (relish), konserve',  # Cranberry-orange relish, canned (yazım/uydurma kelime)
    174206: 'Kabuklular, kerevit, karışık türler, yabani, çiğ',  # Crustaceans, crayfish, mixed species, wild, raw (kural: yanlış çeviri/yazım)
    174207: 'Kabuklular, kerevit, karışık türler, yabani, pişmiş, nemli ısıda pişirilmiş',  # Crustaceans, crayfish, mixed species, wild, cooked, moist he (kural: yanlış çeviri/yazım)
    174471: 'Beç tavuğu (guinea hen), sadece et, çiğ',  # Guinea hen, meat only, raw (yanlış çeviri)
    174535: 'Jambonlu bezelye çorbası (split pea), konserve, düşük sodyumlu, suyla hazırlanmış veya servise hazır',  # Split pea with ham soup, canned, reduced sodium, prepared wi (yanlış çeviri)
    175169: 'Kabuklular, kerevit, karışık türler, çiftlik ürünü, çiğ',  # Crustaceans, crayfish, mixed species, farmed, raw (kural: yanlış çeviri/yazım)
    175170: 'Kabuklular, kerevit, karışık türler, çiftlik ürünü, pişmiş, nemli ısıda pişirilmiş',  # Crustaceans, crayfish, mixed species, farmed, cooked, moist  (kural: yanlış çeviri/yazım)
    175207: 'Fasulyeli chili, konserve',  # Chili with beans, canned (yazım/uydurma kelime)
    175208: 'Börülce, catjang, olgun tohumlar, çiğ',  # Cowpeas, catjang, mature seeds, raw (kural: yanlış çeviri/yazım)
    175209: 'Börülce, catjang, olgun tohumlar, pişmiş, haşlanmış, tuzsuz',  # Cowpeas, catjang, mature seeds, cooked, boiled, without salt (kural: yanlış çeviri/yazım)
    175251: 'Börülce, catjang, olgun tohumlar, pişmiş, haşlanmış, tuzlu',  # Cowpeas, catjang, mature seeds, cooked, boiled, with salt (kural: yanlış çeviri/yazım)
    333374: 'Balık, mezgit (haddock), çiğ',  # Fish, haddock, raw (yanlış çeviri)
    746779: 'Sosis, kahvaltılık, dana eti, önceden pişmiş, hazırlanmamış',  # Sausage, breakfast sausage, beef, pre-cooked, unprepared (yanlış çeviri)
    746780: 'Sosis, İtalyan usulü, domuz eti, hafif, pişmiş, tavada kızarmış',  # Sausage, Italian, pork, mild, cooked, pan-fried (yanlış çeviri)
    746781: 'Sosis, domuz eti, chorizo, bütün veya kıyma, pişmiş, tavada kızarmış',  # Sausage, pork, chorizo, link or ground, cooked, pan-fried (yanlış çeviri)
    746783: 'Sosis, hindi eti, kahvaltılık, hafif, çiğ',  # Sausage, turkey, breakfast links, mild, raw (yanlış çeviri)
    2706171: 'Dana sosisi',  # Beef sausage (yanlış çeviri)
    2706172: 'Peynirli dana sosisi',  # Beef sausage with cheese (yanlış çeviri)
    2706173: 'Kan sosisi',  # Blood sausage (yanlış çeviri)
    2706188: 'Polonya sosisi (kielbasa)',  # Polish sausage (yanlış çeviri)
    2706189: 'İtalyan sosisi',  # Italian sausage (yanlış çeviri)
    2706190: 'Sosis, NFS',  # Sausage, NFS (yanlış çeviri)
    2706191: 'Domuz sosisi',  # Pork sausage (yanlış çeviri)
    2706192: 'Domuz sosisi, düşük yağlı',  # Pork sausage, reduced fat (yanlış çeviri)
    2706193: 'Domuz sosisi, düşük sodyumlu',  # Pork sausage, reduced sodium (yanlış çeviri)
    2706194: 'Domuz ve dana sosisi',  # Pork and beef sausage (yanlış çeviri)
    2706200: 'Hindi veya tavuk sosisi',  # Turkey or chicken sausage (yanlış çeviri)
    2706201: 'Hindi veya tavuk sosisi, düşük sodyumlu',  # Turkey or chicken sausage, reduced sodium (yanlış çeviri)
    2706202: 'Hindi veya tavuk ve domuz sosisi',  # Turkey or chicken and pork sausage (yanlış çeviri)
    2706203: 'Viyana sosisi, konserve',  # Vienna sausage, canned (yanlış çeviri)
    2706204: 'Turşu sosis',  # Pickled sausage (yanlış çeviri)
    2706544: 'İç harçlı (stuffing) tavuk veya hindi',  # Chicken or turkey with stuffing (yanlış çeviri)
    2706687: 'Erişteli tavuk veya hindi chow mein veya chop suey',  # Chicken or turkey chow mein or chop suey with noodles (kural: yanlış çeviri/yazım)
    2706755: 'Domuz incikli lahana',  # Cabbage with ham hocks (yanlış çeviri)
    2706756: 'Jambon veya domuz eti salatası',  # Ham or pork salad (yanlış çeviri)
    2706759: 'Jambonlu veya domuz etli yeşillik',  # Greens with ham or pork (yanlış çeviri)
    2706767: 'Havuç, brokoli ve/veya koyu yeşil yapraklı sebzeler dahil jambon ve sebzeler; patatessiz, sossuz',  # Ham and vegetables including carrots broccoli, and/or dark-  (kural: yanlış çeviri/yazım)
    2706768: 'Havuç, brokoli ve koyu yeşil yapraklı sebzeler hariç jambon ve sebzeler; patatessiz, sossuz',  # Ham and vegetables excluding carrots, broccoli, and dark-gre (kural: yanlış çeviri/yazım)
    2706769: 'Havuç, brokoli ve koyu yeşil yapraklı sebzeler hariç domuz eti ve sebzeler; patatessiz, sossuz',  # Pork and vegetables excluding carrots, broccoli, and dark-gr (yanlış çeviri)
    2706788: 'Havuç, brokoli ve koyu yeşil yapraklı sebzeler hariç sebzeli tavuk veya hindi a la king; patatessiz, krema, beyaz veya çorba bazlı soslu',  # Chicken or turkey a la king with vegetables excluding carror (yanlış çeviri)
    2706874: 'Jambon, balık, peynir ve sebzeli antipasto',  # Antipasto with ham, fish, cheese, vegetables (yanlış çeviri)
    2707036: 'Ton balıklı salata sandviçi, tam buğday ekmeğinde',  # Tuna salad sandwich on wheat (yazım/uydurma kelime)
    2707053: 'İtalyan sosisli sandviç, beyaz ekmekte',  # Italian sausage sandwich on white (yanlış çeviri)
    2707054: 'İtalyan sosisli sandviç, tam buğday ekmeğinde',  # Italian sausage sandwich on wheat (yanlış çeviri)
    2707113: 'Erişte ve peynir soslu tavuk, diyet dondurulmuş öğün',  # Chicken with noodles and cheese sauce, diet frozen meal (kural: yanlış çeviri/yazım)
    2707114: 'Erişteli tavuk ve sebze ana yemeği, diyet dondurulmuş öğün',  # Chicken and vegetable entree with noodles, diet frozen meal (kural: yanlış çeviri/yazım)
    2707116: 'Erişte ve krema soslu tavuk ve sebze ana yemeği, dondurulmuş öğün',  # Chicken and vegetable entree with noodles and cream sauce, f (kural: yanlış çeviri/yazım)
    2707118: 'Soslu ve iç harçlı hindi, patates ve sebze, dondurulmuş öğün',  # Turkey with gravy, dressing, potatoes, vegetable, frozen mea (yanlış çeviri)
    2707120: 'Soslu karides ve sebze, erişte ile, diyet dondurulmuş öğün',  # Shrimp and vegetables in sauce with noodles, diet frozen mea (kural: yanlış çeviri/yazım)
    2707412: 'Börülce (siyah gözlü), NFS',  # Blackeyed peas, NFS (kural: yanlış çeviri/yazım)
    2707413: 'Börülce (siyah gözlü), kurutulmuş',  # Blackeyed peas, from dried (kural: yanlış çeviri/yazım)
    2707437: 'Tofu (soya peyniri)',  # Soybean curd cheese (yazım/uydurma kelime)
    2707466: 'Domuz pastırması (bacon) parçacıkları',  # Bacon bits (yazım/uydurma kelime)
    2708165: 'Patlamış mısır keki',  # Popcorn cake (yanlış çeviri)
    2708216: 'Patlamış mısır, NFS',  # Popcorn, NFS (kural: yanlış çeviri/yazım)
    2708217: 'Patlamış mısır, sinema tipi, ilave tereyağlı',  # Popcorn, movie theater, with added butter (kural: yanlış çeviri/yazım)
    2708218: 'Patlamış mısır, sinema tipi, tereyağı eklenmemiş',  # Popcorn, movie theater, no butter added (kural: yanlış çeviri/yazım)
    2708219: 'Patlamış mısır, hava ile patlatılmış, tereyağı eklenmemiş',  # Popcorn, air-popped, no butter added (kural: yanlış çeviri/yazım)
    2708220: 'Patlamış mısır, hava ile patlatılmış, tereyağı eklenmiş',  # Popcorn, air-popped, with added butter (kural: yanlış çeviri/yazım)
    2708221: 'Patlamış mısır, yağda patlatılmış, tereyağlı değil',  # Popcorn, popped in oil, no butter added (kural: yanlış çeviri/yazım)
    2708222: 'Patlamış mısır, yağda patlatılmış, tereyağı eklenmiş',  # Popcorn, popped in oil, with added butter (kural: yanlış çeviri/yazım)
    2708223: 'Patlamış mısır, mikrodalga, NFS',  # Popcorn, microwave, NFS (kural: yanlış çeviri/yazım)
    2708224: 'Patlamış mısır, mikrodalga, sade',  # Popcorn, microwave, plain (kural: yanlış çeviri/yazım)
    2708225: 'Patlamış mısır, mikrodalga, sade, hafif',  # Popcorn, microwave, plain, light (kural: yanlış çeviri/yazım)
    2708226: 'Patlamış mısır, mikrodalga, düşük sodyumlu',  # Popcorn, microwave, low sodium (kural: yanlış çeviri/yazım)
    2708227: 'Patlamış mısır, mikrodalga, tereyağı aromalı',  # Popcorn, microwave, butter flavored (kural: yanlış çeviri/yazım)
    2708228: 'Patlamış mısır, mikrodalga, aromalı, hafif',  # Popcorn, microwave, flavored, light (kural: yanlış çeviri/yazım)
    2708229: 'Patlamış mısır, mikrodalga, peynir aromalı',  # Popcorn, microwave, cheese flavored (kural: yanlış çeviri/yazım)
    2708230: 'Patlamış mısır, mikrodalga, kazan tipi (kettle)',  # Popcorn, microwave, kettle (kural: yanlış çeviri/yazım)
    2708231: 'Patlamış mısır, hemen tüketimlik, NFS',  # Popcorn, ready-to-eat, NFS (kural: yanlış çeviri/yazım)
    2708232: 'Patlamış mısır, hemen tüketimlik, sade',  # Popcorn, ready-to-eat, plain (kural: yanlış çeviri/yazım)
    2708233: 'Patlamış mısır, hemen tüketimlik, sade, hafif',  # Popcorn, ready-to-eat, plain, light (kural: yanlış çeviri/yazım)
    2708234: 'Patlamış mısır, hemen tüketimlik, düşük sodyumlu',  # Popcorn, ready-to-eat, low sodium (kural: yanlış çeviri/yazım)
    2708235: 'Patlamış mısır, hemen tüketimlik, tereyağı aromalı',  # Popcorn, ready-to-eat, butter flavored (kural: yanlış çeviri/yazım)
    2708236: 'Patlamış mısır, hemen tüketimlik, peynir aromalı',  # Popcorn, ready-to-eat, cheese flavored (kural: yanlış çeviri/yazım)
    2708237: 'Patlamış mısır, hemen tüketimlik, aromalı, hafif',  # Popcorn, ready-to-eat, flavored, light (kural: yanlış çeviri/yazım)
    2708238: 'Patlamış mısır, hemen tüketimlik, kazan tipi (kettle)',  # Popcorn, ready-to-eat, kettle (kural: yanlış çeviri/yazım)
    2708239: 'Patlamış mısır, karamelli kaplama',  # Popcorn, caramel coated (kural: yanlış çeviri/yazım)
    2708240: 'Patlamış mısır, karamelli kaplama, kuruyemişli',  # Popcorn, caramel coated, with nuts (kural: yanlış çeviri/yazım)
    2708241: 'Patlamış mısır, çikolata kaplı',  # Popcorn, chocolate coated (kural: yanlış çeviri/yazım)
    2708243: 'Patlamış mısır cipsi, diğer aromalar',  # Popcorn chips, other flavors (kural: yanlış çeviri/yazım)
    2708244: 'Patlamış mısır cipsi, tatlı aromalar',  # Popcorn chips, sweet flavors (kural: yanlış çeviri/yazım)
    2709019: 'Pirinç, beyaz, koyu yeşil sebzeli ve domatesli ve/veya domates bazlı soslu, yağ ilaveli',  # Rice, white, with dark green vegetables and tomatoes and/or  (yazım/uydurma kelime)
    2709076: 'Pirinç dolgulu domates, etsiz',  # Stuffed tomato, with rice, meatless (yanlış çeviri)
    2709136: 'Sebzeli dürüm (wrap) sandviç',  # Vegetable sandwich wrap (kaymış çeviri bloğu)
    2709137: 'Jöle sandviç, NFS',  # Jelly sandwich, NFS (kaymış çeviri bloğu)
    2709138: 'Jöle sandviç, beyaz ekmek üzerinde',  # Jelly sandwich, on white bread (kaymış çeviri bloğu)
    2709139: 'Jöle sandviç, buğday ekmeği üzerinde',  # Jelly sandwich, on wheat bread (kaymış çeviri bloğu)
    2709140: 'Domates soslu sebzeli erişte, diyet dondurulmuş öğün',  # Noodles with vegetables in tomato-based sauce, diet frozen m (kaymış çeviri bloğu)
    2709141: 'Köfteli spagetti akşam yemeği, NFS, dondurulmuş öğün',  # Spaghetti and meatballs dinner, NFS, frozen meal (kaymış çeviri bloğu)
    2709142: 'Etli spagetti, diyet dondurulmuş öğün',  # Spaghetti with meat sauce, diet frozen meal (kaymış çeviri bloğu)
    2709143: 'Krep ve sosis, dondurulmuş öğün',  # Pancakes and sausage, frozen meal (kaymış çeviri bloğu)
    2709144: 'Çorba, NFS',  # Soup, NFS (kaymış çeviri bloğu)
    2709145: 'Çorba, erişte, NFS',  # Soup, noodle, NFS (kaymış çeviri bloğu)
    2709146: 'Çorba, pirinçli',  # Soup, rice (kaymış çeviri bloğu)
    2709147: 'Çorba, arpa',  # Soup, barley (kaymış çeviri bloğu)
    2709149: 'Çorba, tavuklu şehriye',  # Soup, chicken noodle (kaymış çeviri bloğu)
    2709150: 'Çorba, tavuk, konserve, düşük sodyumlu',  # Soup, chicken, canned, reduced sodium (kaymış çeviri bloğu)
    2709151: 'Çorba, matzo topu',  # Soup, Matzo ball (kaymış çeviri bloğu)
    2709152: 'Çorba, ramen eriştesi, su ilaveli',  # Soup, ramen noodles, water added (kaymış çeviri bloğu)
    2709153: 'Ramen kasesi, NFS',  # Ramen bowl, NFS (kaymış çeviri bloğu)
    2709154: 'Dana etli ramen kasesi',  # Ramen bowl with beef (kaymış çeviri bloğu)
    2709155: 'Tavuklu ramen kasesi',  # Ramen bowl with chicken (kaymış çeviri bloğu)
    2709156: 'Balıklı ramen kasesi',  # Ramen bowl with fish (kaymış çeviri bloğu)
    2709157: 'Vejetaryen ramen kasesi',  # Ramen bowl, vegetarian (kaymış çeviri bloğu)
    2709158: 'Etli ve yumurtalı ramen kasesi',  # Ramen bowl with meat and egg (kaymış çeviri bloğu)
    2709159: 'Yumurtalı vejetaryen ramen kasesi',  # Ramen bowl, vegetarian with egg (kaymış çeviri bloğu)
    2709160: 'Çorba, wonton',  # Soup, wonton (kaymış çeviri bloğu)
    2709161: 'Çorba, sulandırılmış fideo çorbası',  # Soup, sopa de fideo aguada (kaymış çeviri bloğu)
    2709162: 'Çorba, tortilla',  # Soup, tortilla (kaymış çeviri bloğu)
    2709163: 'Tahıl ve sebze proteini bazlı, kızarmış et alternatifi',  # Meat substitute, cereal- and vegetable protein-based, fried (kaymış çeviri bloğu)
    2709164: 'Klementin, çiğ',  # Clementine, raw (kaymış çeviri bloğu)
    2709165: 'Greyfurt, çiğ',  # Grapefruit, raw (kaymış çeviri bloğu)
    2709167: 'Kumkuat, çiğ',  # Kumquat, raw (kaymış çeviri bloğu)
    2709168: 'Limon, çiğ',  # Lemon, raw (kaymış çeviri bloğu)
    2709171: 'Portakal, çiğ',  # Orange, raw (kaymış çeviri bloğu)
    2709172: 'Portakal, konserve, NFS',  # Orange, canned, NFS (kaymış çeviri bloğu)
    2709173: 'Portakal, konserve, meyve suyu paketi',  # Orange, canned, juice pack (kaymış çeviri bloğu)
    2709174: 'Portakal, konserve, şerbetli',  # Orange, canned, in syrup (kaymış çeviri bloğu)
    2709175: 'Mandalina, çiğ',  # Tangerine, raw (kaymış çeviri bloğu)
    2709176: '%100 greyfurt suyu, taze sıkılmış',  # Grapefruit juice, 100%, freshly squeezed (kaymış çeviri bloğu)
    2709177: '%100 greyfurt suyu, formuna göre NS',  # Grapefruit juice, 100%, NS as to form (kaymış çeviri bloğu)
    2709178: '%100 greyfurt suyu, konserve, şişelenmiş veya karton kutuda',  # Grapefruit juice, 100%, canned, bottled or in a carton (kaymış çeviri bloğu)
    2709179: '%100 greyfurt suyu, kalsiyum ilaveli, konserve, şişelenmiş veya karton kutuda',  # Grapefruit juice, 100%, with calcium added (kaymış çeviri bloğu)
    2709180: '%100 limon suyu, formuna göre NS',  # Lemon juice, 100%, NS as to form (kaymış çeviri bloğu)
    2709181: '%100 limon suyu, taze sıkılmış',  # Lemon juice, 100%, freshly squeezed (kaymış çeviri bloğu)
    2709182: '%100 limon suyu, konserve veya şişelenmiş',  # Lemon juice, 100%, canned or bottled (kaymış çeviri bloğu)
    2709183: '%100 misket limonu suyu, formuna göre NS',  # Lime juice, 100%, NS as to form (kaymış çeviri bloğu)
    2709184: '%100 misket limonu suyu, taze sıkılmış',  # Lime juice, 100%, freshly squeezed (kaymış çeviri bloğu)
    2709185: '%100 misket limonu suyu, konserve veya şişelenmiş',  # Lime juice, 100%, canned or bottled (kaymış çeviri bloğu)
    2709186: '%100 portakal suyu, NFS',  # Orange juice, 100%, NFS (kaymış çeviri bloğu)
    2709187: '%100 portakal suyu, taze sıkılmış',  # Orange juice, 100%,  freshly squeezed (kaymış çeviri bloğu)
    2709188: '%100 portakal suyu, konserve, şişelenmiş veya karton kutuda',  # Orange juice, 100%, canned, bottled or in a carton (kaymış çeviri bloğu)
    2709189: '%100 portakal suyu, kalsiyum ilaveli, konserve, şişelenmiş veya karton kutuda',  # Orange juice, 100%, with calcium added, canned, bottled or i (kaymış blok + yazım)
    2709190: '%100 portakal suyu, dondurulmuş, yeniden hazırlanmış',  # Orange juice, 100%, frozen, reconstituted (kaymış çeviri bloğu)
    2709191: '%100 portakal suyu, dondurulmuş, yeniden hazırlanmamış',  # Orange juice, 100%, frozen, not reconstituted (kaymış çeviri bloğu)
    2709192: '%100 portakal suyu, kalsiyum ilaveli, dondurulmuş, yeniden hazırlanmış',  # Orange juice, 100%, with calcium added, frozen, reconstitute (kaymış çeviri bloğu)
    2709193: '%100 mandalina suyu',  # Tangerine juice, 100% (kaymış çeviri bloğu)
    2709194: 'Meyve suyu karışımı, narenciye, %100 meyve suyu',  # Fruit juice blend, citrus, 100% juice (kaymış çeviri bloğu)
    2709195: 'Kuru meyve, NFS',  # Dried, fruit, NFS (kaymış blok)
    2709268: 'Ravent (rhubarb)',  # Rhubarb (yanlış çeviri)
    2709754: 'Jambonlu Porto Riko baharatı',  # Puerto Rican seasoning with ham (yanlış çeviri)
    2709755: 'Jambonsuz ve domates sossuz Porto Riko baharatı',  # Puerto Rican seasoning without ham and tomato sauce (yanlış çeviri)
    2709767: 'Kuşkonmaz, çiğ',  # Asparagus, raw (yazım/uydurma kelime)
    2709788: 'Alabaş (kohlrabi), çiğ',  # Kohlrabi, raw (yazım/uydurma kelime)
    2709804: 'İsveç şalgamı (rutabaga), çiğ',  # Rutabaga, raw (yanlış çeviri)
    2709819: 'Ekşi krema soslu salatalık salatası',  # Cucumber salad, made with sour cream dressing (yanlış çeviri)
    2709834: 'Kuşkonmaz, taze, pişmiş, ilave yağsız',  # Asparagus, fresh, cooked, no added fat (kural: yanlış çeviri/yazım)
    2709835: 'Kuşkonmaz, dondurulmuş, pişmiş, ilave yağsız',  # Asparagus, frozen, cooked, no added fat (kural: yanlış çeviri/yazım)
    2709836: 'Kuşkonmaz, konserve, pişmiş, ilave yağsız',  # Asparagus, canned, cooked, no added fat (kural: yanlış çeviri/yazım)
    2709837: 'Kuşkonmaz, form fark etmeksizin, pişmiş',  # Asparagus, NS as to form, cooked (kural: yanlış çeviri/yazım)
    2709838: 'Kuşkonmaz, taze, pişmiş, yağ eklenmiş, yağ türü belirtilmemiş',  # Asparagus, fresh, cooked, fat added, NS as to fat type (kural: yanlış çeviri/yazım)
    2709839: 'Kuşkonmaz, dondurulmuş, pişmiş, yağ eklenmiş, yağ türü belirtilmemiş',  # Asparagus, frozen, cooked, fat added, NS as to fat type (kural: yanlış çeviri/yazım)
    2709840: 'Kuşkonmaz, konserve, pişmiş, yağ eklenmiş, yağ türü belirtilmemiş',  # Asparagus, canned, cooked, fat added, NS as to fat type (kural: yanlış çeviri/yazım)
    2709841: 'Kuşkonmaz, taze, yağ ile pişmiş',  # Asparagus, fresh, cooked with oil (kural: yanlış çeviri/yazım)
    2709842: 'Kuşkonmaz, taze, tereyağı veya margarin ile pişmiş',  # Asparagus, fresh, cooked with butter or margarine (kural: yanlış çeviri/yazım)
    2709843: 'Kuşkonmaz, dondurulmuş, yağ ile pişmiş',  # Asparagus, frozen, cooked with oil (kural: yanlış çeviri/yazım)
    2709844: 'Kuşkonmaz, dondurulmuş, tereyağı veya margarin ile pişmiş',  # Asparagus, frozen, cooked with butter or margarine (kural: yanlış çeviri/yazım)
    2709845: 'Kuşkonmaz, konserve, yağ ile pişmiş',  # Asparagus, canned, cooked with oil (kural: yanlış çeviri/yazım)
    2709846: 'Kuşkonmaz, konserve, tereyağı veya margarin ile pişmiş',  # Asparagus, canned, cooked with butter or margarine (kural: yanlış çeviri/yazım)
    2709955: 'Yaban havucu (parsnip), pişmiş',  # Parsnips, cooked (kural: yanlış çeviri/yazım)
    2709956: 'Börülce (siyah gözlü), dondurulmuş',  # Blackeyed peas, from frozen (kural: yanlış çeviri/yazım)
    2709957: 'Börülce (siyah gözlü), konserve',  # Blackeyed peas, from canned (kural: yanlış çeviri/yazım)
    2709980: 'İsveç şalgamı (rutabaga), pişmiş',  # Rutabaga, cooked (yanlış çeviri)
    2710002: 'Şalgam, pişmiş',  # Turnip, cooked (yanlış çeviri)
    2710011: 'Biber ve soğan, pişmiş, yağ eklenmiş',  # Peppers and onions, cooked, fat added (yazım/uydurma kelime)
    2710083: 'Yaban turpu (horseradish)',  # Horseradish (yanlış çeviri)
    2710343: 'Hindistan cevizi dolgulu çikolatalı şekerleme',  # Chocolate candy, coconut filled (yanlış çeviri)
    2710540: 'Su, gazlı, aromalı',  # Water, carbonated, flavored (kural: yanlış çeviri/yazım)
    2710708: 'Su, şişelenmiş, sade',  # Water, bottled, plain (kural: yanlış çeviri/yazım)
    2710777: 'Meyve suyu, açai karışımı',  # Fruit juice, acai blend (isim yerine çeviri prompt'u)
}


def apply_name_fixes(db) -> int:
    """Düzeltmeleri uygular, değişen satır sayısını döner (idempotent)."""
    changed = 0
    for row in db.query(FoodCatalog).filter(FoodCatalog.fdc_id.in_(list(NAME_FIXES))):
        name = NAME_FIXES[row.fdc_id]
        if row.name_tr != name:
            row.name_tr = name
            changed += 1
    db.commit()
    food_catalog_service.invalidate_cache()
    return changed


if __name__ == "__main__":
    session = SessionLocal()
    try:
        print(f"[food_catalog] {apply_name_fixes(session)} isim düzeltildi")
    finally:
        session.close()
