"""Yasal metinlerin TEK kaynağı (2026-10-05, Cloudvist/Türkiye barındırma).

Biçim: her belge (kind, ...) öğelerinden oluşan bir liste.
  ("h2", id, başlık)   bölüm başlığı (id: web anchor + mobil section param)
  ("h3", metin)        alt başlık
  ("p", metin)         paragraf
  ("hl", metin)        vurgulu kutu (yalnız Koşullar)
Satır içi: **kalın**, [[email]] = iletişim adresi, [[kvkk|metin]] = KVKK sayfası
bağlantısı (web Link, mobilde düz metin), \\n = satır sonu.
"""

UPDATED_TR = "5 Ekim 2026"
UPDATED_EN = "October 5, 2026"

KVKK_TR = [
    ("h2", "aydinlatma", "1. Aydınlatma Metni"),
    ("p", f"Son güncelleme: {UPDATED_TR}. Bu metin, 6698 sayılı Kişisel Verilerin Korunması Kanunu (\"KVKK\") madde 10 ve Aydınlatma Yükümlülüğünün Yerine Getirilmesinde Uyulacak Usul ve Esaslar Hakkında Tebliğ uyarınca, PulseCoach'u kullanırken işlenen kişisel verileriniz hakkında sizi bilgilendirmek için hazırlanmıştır. Aydınlatma metni bir onay metni değildir; sağlık verilerinizin işlenmesine ilişkin açık rızanız aşağıdaki 2. bölümde ayrıca istenir."),

    ("h3", "1.1 Veri Sorumlusu"),
    ("p", "PulseCoach, gerçek kişi Bora Eren Erdem tarafından bireysel ve ticari kâr amacı gütmeyen bir proje olarak işletilmektedir. KVKK kapsamında veri sorumlusu Bora Eren Erdem'dir (\"biz\"). İletişim ve KVKK başvuruları: [[email]]."),

    ("h3", "1.2 İşlenen Kişisel Veriler ve Hukuki Sebepleri"),
    ("p", "**Kimlik ve iletişim:** e-posta adresiniz; isteğe bağlı görünen adınız, doğum yılınız ve cinsiyetiniz (son ikisi yalnız kalori önerisi için). Google veya Apple ile giriş yaparsanız bu sağlayıcının bize ilettiği e-posta adresi ve hesap kimliği (Apple'da \"E-postamı Gizle\"yi seçerseniz Apple'ın aktarıcı adresi). Hukuki sebep: sözleşmenin kurulması ve ifası (KVKK md. 5/2-c)."),
    ("p", "**Hesap ve işlem güvenliği:** şifreniz (geri döndürülemez biçimde hash'lenmiş), oturum jetonları, giriş ve şifre sıfırlama denemeleri, IP adresiniz ve isteklerin zamanı. Hukuki sebep: sözleşmenin ifası (md. 5/2-c), veri güvenliğini sağlama yükümlülüğümüz (md. 5/2-ç, md. 12) ve hesabınızı ve sistemi kötüye kullanıma karşı korumaya yönelik meşru menfaatimiz (md. 5/2-f)."),
    ("p", "**Sağlık ve yaşam tarzı verileri (özel nitelikli kişisel veri):** antrenman ve egzersiz kayıtlarınız (set, tekrar, ağırlık, süre, kardiyo), beslenme kayıtlarınız ve yemek fotoğraflarınız, vücut ölçümleriniz (kilo, boy, bel çevresi, vücut yağ oranı), hedefleriniz, profilde belirttiğiniz beslenme kısıtlamaları ve alerjiler, ruh hâli kayıtlarınız, yapay zekâ koç ile sohbet geçmişiniz ve bu verilere dayanan koç mesajları (check-in'ler). Hukuki sebep: **yalnızca açık rızanız** (KVKK md. 6/3-a; bkz. 2. bölüm)."),
    ("p", "**Uygulama tercihleri ve teknik veriler:** dil, koç tonu, bildirim tercihleri ve hatırlatma saati, saat diliminiz ve günlük kullanım sayaçları. Hukuki sebep: sözleşmenin ifası (md. 5/2-c)."),
    ("p", "**Onay ve başvuru kayıtları:** kayıt sırasında verdiğiniz onayların tarihi ve metin sürümü, KVKK başvurularınız ve bizimle yazışmalarınız. Hukuki sebep: hukuki yükümlülüklerimizin yerine getirilmesi (md. 5/2-ç) ve bir hakkın tesisi, kullanılması veya korunması (md. 5/2-e)."),

    ("h3", "1.3 İşleme Amaçları"),
    ("p", "Hesabınızı oluşturmak ve yönetmek; antrenman, beslenme, vücut ölçümü ve ruh hâli takibi sunmak; yapay zekâ koç aracılığıyla size özel geri bildirim, özet ve öneri üretmek; yemek fotoğraflarınızdaki besinleri tanımak; uygulama içi koç mesajları ve hatırlatmalar üretmek; hesap ve sistem güvenliğini sağlamak (kimlik doğrulama, deneme sınırlaması, şifre sıfırlama, günlük kullanım kotası); KVKK başvurularınızı ve taleplerinizi yanıtlamak; yasal yükümlülüklerimizi yerine getirmek. Verileriniz reklam, pazarlama veya profilleme yoluyla satış amacıyla işlenmez."),

    ("h3", "1.4 Toplama Yöntemi"),
    ("p", "Kişisel verileriniz uygulamayı kullanırken doğrudan sizden (kayıt ve profil formları, kayıt ekranları, sohbet, fotoğraf yükleme) elektronik ortamda; Google veya Apple ile giriş yaparsanız bu sağlayıcılardan; IP adresi ve istek zamanı gibi teknik kayıtlar ise sistem tarafından otomatik olarak toplanır."),

    ("h3", "1.5 Yapay Zekâ Koç ve Otomatik İşleme"),
    ("p", "Yapay zekâ koç ve yemek fotoğrafı analizi, **Türkiye'deki kendi sunucumuzda çalışan açık kaynaklı dil ve görüntü modelleriyle** yapılır. Sohbetleriniz, fotoğraflarınız ve sağlık verileriniz OpenAI, Google veya benzeri üçüncü taraf yapay zekâ hizmetlerine **gönderilmez** ve modelleri eğitmek için **kullanılmaz**. Koçun önerileri verilerinizden otomatik olarak üretilir; ancak hakkınızda hukuki sonuç doğuran veya sizi önemli ölçüde etkileyen otomatik bir karar alınmaz. Münhasıran otomatik sistemlerle analiz sonucu aleyhinize bir sonuç çıktığını düşünürseniz buna itiraz edebilirsiniz (1.10)."),

    ("h3", "1.6 Kişisel Verilerin Aktarılması"),
    ("p", "**Yurt içi:** Uygulama, veritabanı ve yapay zekâ modelleri, Türkiye'deki bir veri merkezinde bulunan ve **Cloudvist Bilişim Teknolojileri (İstanbul)** tarafından sağlanan sunucuda çalışır; hesap, sağlık ve sohbet verileriniz yalnızca bu sunucuda saklanır ve işlenir. Sağlayıcı, KVKK md. 12 anlamında veri işleyen sıfatıyla yalnızca altyapıyı (donanım, elektrik, ağ) sağlar. Veritabanı yedekleri sunucudan çıkmadan şifrelenir ve **Türkiye'de** ayrı bir depolama ortamında tutulur. Tek işlemsel e-postamız olan şifre sıfırlama e-postası ve [[email]] adresine yazdığınız e-postalar, **Türkiye'de yerleşik** e-posta hizmet sağlayıcısı **Uzman Posta (Pusula İletişim, İstanbul)** aracılığıyla gönderilir ve alınır; bu sağlayıcı da yalnızca veri işleyen sıfatıyla hizmet verir. Kanunen yetkili kamu kurum ve kuruluşları ile yargı mercilerine, yalnızca yasal bir talep veya zorunluluk hâlinde aktarım yapılabilir."),
    ("p", "**Bildirimler:** Bildirimleri açarsanız hatırlatma ve haftalık özet bildirimleri **cihazınızda yerel olarak** zamanlanır; sunucumuz bildirim göndermez, bu amaçla bildirim jetonu toplamaz ve hiçbir bildirim servisine veri aktarmaz. Bildirim metinleri genel niteliktedir ve sağlık verisi içermez. Bildirimleri dilediğiniz zaman cihaz ayarlarından veya Profil > Bildirimler bölümünden kapatabilirsiniz; bildirimleri açmamanız uygulamanın diğer işlevlerini etkilemez."),
    ("p", "**E-posta teslimi ve Google/Apple ile giriş:** E-postalarımız, bize verdiğiniz adrese teslim edilir; adresiniz yurt dışında sunucusu bulunan bir sağlayıcıdaysa (ör. Gmail, Outlook, iCloud veya Apple'ın \"E-postamı Gizle\" aktarıcısı) e-posta o sağlayıcının sunucularına ulaşır. Bu nedenle e-postalarımıza sağlık verisi koymayız; uygulama yalnızca şifre sıfırlama bağlantısı gönderir. Google veya Apple ile giriş yaptığınızda kimliğinizi bu sağlayıcıların yayımladığı açık anahtarlarla doğrularız; bu sağlayıcılara sizinle ilgili bir veri göndermeyiz. Web sürümünde giriş ekranındaki \"Google ile devam edin\" düğmesi Google'ın sunucularından yüklenir; bu sırada tarayıcınız Google'a IP adresi gibi teknik bilgiler iletir ve bu işlem Google'ın kendi gizlilik koşullarına tabidir. Bunu istemiyorsanız e-posta ve şifreyle kayıt olabilirsiniz."),
    ("p", "Verileriniz hiçbir koşulda **reklam veya pazarlama amacıyla üçüncü kişilere satılmaz, kiralanmaz veya paylaşılmaz**; uygulamada reklam, analitik veya izleme aracı bulunmaz."),

    ("h3", "1.7 Saklama Süreleri"),
    ("p", "**Hesap ve sağlık verileri:** hesabınız açık olduğu sürece; hesabınızı sildiğinizde (Profil > Hesabımı Sil) derhal ve kalıcı olarak.\n**Yemek fotoğrafları:** en fazla 12 ay ve kişi başına en yeni 200 fotoğraf; daha eskileri otomatik silinir.\n**Giriş ve şifre sıfırlama denemeleri (e-posta/IP):** 7 gün.\n**Sunucu erişim kayıtları (IP adresi, istek zamanı ve yolu):** 14 gün.\n**Şifre sıfırlama bağlantıları:** 1 saat geçerlidir ve tek kullanımlıktır.\n**Yedekler:** sunucuda 14 gün, Türkiye'deki ayrı yedekte 30 gün; silinen hesabın verileri yedeklerden en geç 30 gün içinde kendiliğinden çıkar ve bu sürede yedekler yalnızca bir arızadan sonra sistemi geri yüklemek için kullanılır.\n**Onay ve başvuru kayıtları:** talebin sonuçlandırılması ve olası uyuşmazlıklar için gerekli süre boyunca, en fazla 10 yıl.\nSüresi dolan veriler, Kişisel Verilerin Silinmesi, Yok Edilmesi veya Anonim Hale Getirilmesi Hakkında Yönetmelik'e uygun olarak silinir."),

    ("h3", "1.8 Veri Güvenliği Tedbirleri"),
    ("p", "Şifreniz geri döndürülemez biçimde hash'lenerek saklanır ve tarafımızca dahi okunamaz. Uygulama ile sunucu arasındaki tüm iletişim şifrelenir (HTTPS/TLS). Veritabanı internete kapalıdır; sunucuya yalnızca veri sorumlusu, anahtar tabanlı kimlik doğrulamayla erişir. Yedekler şifrelenir; deneme sınırlaması ve günlük kullanım kotası kötüye kullanımı önler. Özel nitelikli kişisel veriler için Kişisel Verileri Koruma Kurulunun belirlediği yeterli önlemler esas alınır. Bir veri ihlali öğrenmemiz hâlinde Kurul'a en geç 72 saat içinde, etkilenen kullanıcılara ise en kısa sürede bildirim yapılır. İnternet üzerinden hiçbir iletim veya saklama yönteminin yüzde yüz güvenli olmadığını hatırlatırız."),

    ("h3", "1.9 Çerezler, Yerel Depolama ve Yaş Sınırı"),
    ("p", "Uygulama reklam, analitik veya izleme amaçlı çerez kullanmaz. Oturumunuzu açık tutan giriş jetonları, dil ve tema tercihiniz ile zamanlanmış bildirimleriniz yalnızca cihazınızda (tarayıcı belleği veya mobil cihaz deposu) tutulur. PulseCoach 18 yaşından küçükler için tasarlanmamıştır; 18 yaşından küçüklerin uygulamayı kullanmasına izin verilmez. 18 yaş altı bir kullanıcıya ait veri fark edersek bu veriyi sileriz; bu konuda [[email]] adresinden bize ulaşabilirsiniz."),

    ("h3", "1.10 Haklarınız ve Başvuru Usulü (KVKK md. 11)"),
    ("p", "Bize başvurarak (a) kişisel verinizin işlenip işlenmediğini öğrenme, (b) işlenmişse buna ilişkin bilgi talep etme, (c) işlenme amacını ve amacına uygun kullanılıp kullanılmadığını öğrenme, (ç) yurt içinde veya yurt dışında aktarıldığı üçüncü kişileri bilme, (d) eksik veya yanlış işlenmişse düzeltilmesini isteme, (e) KVKK md. 7 çerçevesinde silinmesini veya yok edilmesini isteme, (f) (d) ve (e) kapsamındaki işlemlerin aktarıldığı üçüncü kişilere bildirilmesini isteme, (g) münhasıran otomatik sistemlerle analiz edilmesi sonucu aleyhinize bir sonuç çıkmasına itiraz etme ve (ğ) kanuna aykırı işleme nedeniyle zarara uğramanız hâlinde zararın giderilmesini talep etme haklarına sahipsiniz."),
    ("p", "Başvurunuzu, Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ uyarınca, **uygulamaya kayıtlı e-posta adresinizden** [[email]] adresine e-posta göndererek ya da güvenli elektronik imza, mobil imza veya kayıtlı elektronik posta (KEP) ile iletebilirsiniz. Başvuruda adınız, soyadınız, kimlik bilgileriniz, tebligata esas adresiniz veya e-posta adresiniz ve talebinizin konusu yer almalıdır. Başvurunuz talebin niteliğine göre en geç otuz gün içinde ücretsiz sonuçlandırılır; işlemin ayrıca bir maliyet gerektirmesi hâlinde Kurul'ca belirlenen tarifedeki ücret alınabilir. Başvurunuz reddedilir, cevabı yetersiz bulunur veya süresinde cevap verilmezse, cevabı öğrendiğiniz tarihten itibaren otuz gün ve her hâlde başvuru tarihinden itibaren altmış gün içinde Kişisel Verileri Koruma Kuruluna şikâyette bulunabilirsiniz. Ayrıca uygulamada Profil > Verilerim bölümünden tüm verilerinizi indirebilir, Profil > Hesabımı Sil bölümünden hesabınızı ve verilerinizi kalıcı olarak silebilirsiniz."),

    ("h3", "1.11 Metin Güncellemeleri"),
    ("p", "Bu metinde değişiklik yaptığımızda güncelleme tarihi yukarıda belirtilir ve önemli değişiklikler uygulama içinden duyurulur. Açık rızaya dayanan işlemelerde kapsam genişlerse rızanız yeniden istenir."),

    ("h2", "saglik-verisi", "2. Sağlık Verilerinin İşlenmesine İlişkin Açık Rıza Metni"),
    ("p", "PulseCoach'u kullanırken paylaşacağım antrenman ve egzersiz kayıtlarımın, beslenme kayıtlarımın ve yemek fotoğraflarımın, kilo, boy, bel çevresi ve vücut yağ oranı gibi vücut ölçümlerimin, hedeflerimin, beslenme kısıtlamalarım ve alerjilerimin, ruh hâli kayıtlarımın ve bu verilere dayanarak yapay zekâ koç ile yaptığım sohbetlerin KVKK md. 6 kapsamında **özel nitelikli kişisel veri (sağlık verisi)** olduğunu biliyorum."),
    ("p", "Aydınlatma Metni'nde açıklandığı üzere bu verilerin, bana kişiselleştirilmiş antrenman ve beslenme takibi, ilerleme analizi ve yapay zekâ koçluk hizmeti sunulması amacıyla, Türkiye'deki sunucuda veri sorumlusu Bora Eren Erdem tarafından işlenmesine, saklanmasına ve bu sunucunun barındırma hizmetini sağlayan veri işleyene emanet edilmesine **AÇIK RIZA VERİYORUM**. Bu verilerin yurt dışına aktarılmayacağı, üçüncü taraf yapay zekâ hizmetlerine gönderilmeyeceği ve reklam/pazarlama amacıyla kullanılmayacağı konusunda bilgilendirildim."),
    ("p", "Açık rızamın özgür irademe dayandığını; ancak koçluk hizmetinin doğası gereği bu veriler işlenmeden uygulamanın temel işlevlerinin sunulamayacağını biliyorum. Rızamı dilediğim zaman Profil > Hesabımı Sil bölümünden ya da [[email]] adresine yazarak geri çekebilirim; geri çekmem ileriye etkili olur, sağlık verilerim silinir ve hizmetin bu verilere dayanan bölümü sona erer."),
    ("p", "Yapay zekâ koçun önerilerinin genel bilgilendirme amaçlı olduğunu, tıbbi teşhis veya tedavi yerine geçmediğini ve sağlığımla ilgili kararlar için bir hekime veya diyetisyene danışmam gerektiğini biliyorum (bkz. Kullanım Koşulları)."),
]

KVKK_EN = [
    ("h2", "aydinlatma", "1. Privacy Notice"),
    ("p", f"Last updated: {UPDATED_EN}. This notice explains, in line with Article 10 of Turkey's Law No. 6698 on the Protection of Personal Data (\"KVKK\") and the Communiqué on the Procedures and Principles for the Obligation to Inform, how your personal data is processed while you use PulseCoach. This notice is not a consent form; your explicit consent to the processing of your health data is requested separately in section 2."),

    ("h3", "1.1 Data Controller"),
    ("p", "PulseCoach is operated by Bora Eren Erdem, a natural person, as an individual, non-commercial project. Bora Eren Erdem is the data controller under KVKK (\"we\"). Contact and data protection requests: [[email]]."),

    ("h3", "1.2 Personal Data We Process and Legal Bases"),
    ("p", "**Identity and contact:** your email address; optionally your display name, birth year and sex (the latter two only for the calorie suggestion). If you sign in with Google or Apple, the email address and account identifier that provider shares with us (with Apple's \"Hide My Email\", Apple's relay address). Legal basis: establishment and performance of the contract (KVKK Art. 5/2-c)."),
    ("p", "**Account and transaction security:** your password (stored irreversibly hashed), session tokens, sign-in and password reset attempts, your IP address and request times. Legal basis: performance of the contract (Art. 5/2-c), our legal obligation to keep data secure (Art. 5/2-ç, Art. 12), and our legitimate interest in protecting your account and the system against abuse (Art. 5/2-f)."),
    ("p", "**Health and lifestyle data (special category personal data):** your workout and exercise records (sets, reps, weight, duration, cardio), nutrition logs and meal photos, body measurements (weight, height, waist circumference, body fat percentage), goals, dietary restrictions and allergies you enter in your profile, mood logs, your chat history with the AI coach, and coach messages based on this data (check-ins). Legal basis: **your explicit consent only** (KVKK Art. 6/3-a; see section 2)."),
    ("p", "**App preferences and technical data:** language, coach tone, notification preferences and reminder time, your time zone and daily usage counters. Legal basis: performance of the contract (Art. 5/2-c)."),
    ("p", "**Consent and request records:** the date and text version of the confirmations you give at sign-up, your data protection requests and our correspondence. Legal basis: fulfilling our legal obligations (Art. 5/2-ç) and establishing, exercising or protecting a right (Art. 5/2-e)."),

    ("h3", "1.3 Purposes of Processing"),
    ("p", "Creating and managing your account; providing workout, nutrition, body measurement and mood tracking; generating personalized feedback, summaries and recommendations through the AI coach; recognizing foods in your meal photos; generating in-app coach messages and reminders; securing your account and the system (authentication, rate limiting, password resets, daily usage quota); responding to your data protection requests; and complying with our legal obligations. Your data is not processed for advertising, marketing or sale through profiling."),

    ("h3", "1.4 How Data Is Collected"),
    ("p", "Your personal data is collected electronically, directly from you while you use the app (sign-up and profile forms, logging screens, chat, photo uploads); from Google or Apple if you sign in with them; and technical records such as IP address and request time are collected automatically by the system."),

    ("h3", "1.5 AI Coach and Automated Processing"),
    ("p", "The AI coach and meal photo analysis run on **open-source language and vision models hosted on our own server in Turkey**. Your chats, photos and health data are **never sent** to third-party AI services such as OpenAI or Google and are **not used** to train models. The coach's recommendations are generated automatically from your data; however, no automated decision producing legal effects or similarly significantly affecting you is made. If you believe an exclusively automated analysis led to a result to your detriment, you can object (1.10)."),

    ("h3", "1.6 Data Transfers"),
    ("p", "**Within Turkey:** The app, database and AI models run on a server located in a data center in Turkey and provided by **Cloudvist Bilişim Teknolojileri (Istanbul)**; your account, health and chat data is stored and processed only on this server. The provider acts as a data processor under KVKK Art. 12 and supplies only the infrastructure (hardware, power, network). Database backups are encrypted before they leave the server and are kept on separate storage **in Turkey**. Our only transactional email, the password reset email, and the emails you send to [[email]] are sent and received through **Uzman Posta (Pusula İletişim, Istanbul)**, an email service provider **established in Turkey**, which also acts only as a data processor. Data may be disclosed to competent public authorities and courts only upon a lawful request or obligation."),
    ("p", "**Notifications:** If you enable notifications, reminder and weekly summary notifications are scheduled **locally on your device**; our server does not send notifications, does not collect a notification token for this purpose and does not transfer any data to a notification service. Notification texts are generic and contain no health data. You can turn notifications off at any time in your device settings or in Profile > Notifications; not enabling notifications does not affect any other feature."),
    ("p", "**Email delivery and Google/Apple sign-in:** Our emails are delivered to the address you give us; if your address is with a provider whose servers are abroad (e.g. Gmail, Outlook, iCloud or Apple's \"Hide My Email\" relay), the email reaches that provider's servers. For this reason we never put health data in emails; the app only sends password reset links. When you sign in with Google or Apple, we verify your identity using the public keys those providers publish; we do not send them any data about you. On the web version, the \"Continue with Google\" button on the sign-in screen is loaded from Google's servers; while it loads, your browser sends Google technical information such as your IP address, which is subject to Google's own privacy terms. If you prefer to avoid this, you can sign up with email and password."),
    ("p", "Your data is **never sold, rented or shared with third parties for advertising or marketing**; the app contains no advertising, analytics or tracking tools."),

    ("h3", "1.7 Retention Periods"),
    ("p", "**Account and health data:** as long as your account is open; deleted immediately and permanently when you delete your account (Profile > Delete My Account).\n**Meal photos:** at most 12 months and the latest 200 photos per person; older ones are deleted automatically.\n**Sign-in and password reset attempts (email/IP):** 7 days.\n**Server access logs (IP address, request time and path):** 14 days.\n**Password reset links:** valid for 1 hour and single-use.\n**Backups:** 14 days on the server and 30 days in the separate backup in Turkey; data of a deleted account drops out of backups automatically within 30 days at the latest, and during that time backups are used only to restore the system after a failure.\n**Consent and request records:** for as long as needed to resolve the request and any dispute, at most 10 years.\nData whose retention period has expired is deleted in line with the Regulation on the Deletion, Destruction or Anonymization of Personal Data."),

    ("h3", "1.8 Data Security Measures"),
    ("p", "Your password is stored irreversibly hashed and cannot be read even by us. All communication between the app and the server is encrypted (HTTPS/TLS). The database is not reachable from the internet; only the data controller accesses the server, using key-based authentication. Backups are encrypted; rate limiting and a daily usage quota prevent abuse. The adequate measures set by the Personal Data Protection Board for special category data are applied. If we learn of a data breach, we notify the Board within 72 hours at the latest and the affected users as soon as possible. Please note that no method of transmission or storage over the internet is 100% secure."),

    ("h3", "1.9 Cookies, Local Storage and Age Limit"),
    ("p", "The app does not use cookies for advertising, analytics or tracking. The tokens that keep you signed in, your language and theme preference and your scheduled notifications are stored only on your device (browser storage or mobile device storage). PulseCoach is not designed for children; users under 18 are not allowed to use the app. If we become aware of data belonging to a user under 18, we delete it; you can reach us about this at [[email]]."),

    ("h3", "1.10 Your Rights and How to Apply (KVKK Art. 11)"),
    ("p", "You may contact us to (a) learn whether your personal data is processed, (b) request information about it if so, (c) learn the purpose of processing and whether data is used accordingly, (d) know the third parties to whom it is transferred in Turkey or abroad, (e) request correction if it is incomplete or inaccurate, (f) request erasure or destruction under KVKK Art. 7, (g) request that actions under (e) and (f) be notified to third parties it was transferred to, (h) object to a result to your detriment arising exclusively from automated analysis, and (i) claim compensation for damage caused by unlawful processing."),
    ("p", "Under the Communiqué on the Procedures and Principles of Application to the Data Controller, you can apply by emailing [[email]] **from the email address registered in the app**, or by secure electronic signature, mobile signature or registered electronic mail (KEP). Your application should include your name, surname, identity details, an address or email address for notification and the subject of your request. We respond free of charge within thirty days at the latest depending on the nature of the request; if the action requires additional cost, a fee set by the Board may apply. If your application is rejected, the response is insufficient or no response is given in time, you can file a complaint with the Personal Data Protection Board within thirty days of learning the response and in any case within sixty days of the application date. You can also download all your data from Profile > My Data and permanently delete your account and data from Profile > Delete My Account."),

    ("h3", "1.11 Changes to This Notice"),
    ("p", "When we change this notice, the update date above changes and material changes are announced in the app. If the scope of processing based on explicit consent expands, your consent is requested again."),

    ("h2", "saglik-verisi", "2. Explicit Consent for Processing Health Data"),
    ("p", "I understand that the workout and exercise records, nutrition logs and meal photos, body measurements such as weight, height, waist circumference and body fat percentage, goals, dietary restrictions and allergies, mood logs, and chats with the AI coach based on this data that I share while using PulseCoach are **special category personal data (health data)** under KVKK Art. 6."),
    ("p", "As explained in the Privacy Notice, I **GIVE MY EXPLICIT CONSENT** for this data to be processed and stored by the data controller Bora Eren Erdem on the server in Turkey, and entrusted to the data processor providing that server's hosting, for the purpose of providing me with personalized workout and nutrition tracking, progress analysis and AI coaching. I have been informed that this data will not be transferred abroad, will not be sent to third-party AI services and will not be used for advertising or marketing."),
    ("p", "I understand that my consent is freely given, but that by the nature of the coaching service the app's core features cannot be provided without processing this data. I can withdraw my consent at any time from Profile > Delete My Account or by writing to [[email]]; withdrawal takes effect for the future, my health data is deleted and the part of the service relying on it ends."),
    ("p", "I understand that the AI coach's recommendations are for general information only, do not replace medical diagnosis or treatment, and that I should consult a physician or dietitian for decisions about my health (see the Terms of Service)."),
]

TERMS_TR = [
    ("p", f"Son güncelleme: {UPDATED_TR}. Bu Kullanım Koşulları (\"Koşullar\"), PulseCoach'u (\"Uygulama\") kullanan herkes (\"Kullanıcı\", \"siz\") ile Uygulamayı işleten Bora Eren Erdem (\"biz\") arasındaki ilişkiyi düzenler. Kişisel verilerinizin nasıl işlendiği [[kvkk|Gizlilik ve KVKK]] metninde açıklanmıştır."),
    ("h2", "kabul", "1. Taraflar ve Kabul"),
    ("p", "PulseCoach, gerçek kişi Bora Eren Erdem tarafından bireysel ve ticari kâr amacı gütmeyen bir proje olarak işletilmektedir. Hesap oluştururken bu Koşulları onaylayarak ya da Uygulamayı kullanarak Koşulları okuduğunuzu ve kabul ettiğinizi beyan edersiniz. Koşulları kabul etmiyorsanız Uygulamayı kullanmamalısınız."),
    ("h2", "hizmet", "2. Hizmetin Tanımı"),
    ("p", "PulseCoach; antrenman, beslenme, ruh hâli ve vücut ölçümü takibi ile bu verilere dayanan, yapay zekâ destekli kişiselleştirilmiş öneriler sunan bir mobil ve web uygulamasıdır. Yapay zekâ koç ve yemek fotoğrafı analizi, Türkiye'deki sunucumuzda çalışan açık kaynaklı modellerle yapılır. Yapay zekâ **hata yapabilir**: kalori, makro, egzersiz ve fotoğraftan tahmin edilen miktarlar yaklaşıktır; kayıtlarınızı kontrol etmeniz ve önemli kararları yalnızca bu çıktılara dayandırmamanız gerekir."),
    ("h2", "uygunluk", "3. Uygunluk ve Hesap"),
    ("p", "Uygulamayı kullanmak için **en az 18 yaşında** olmanız gerekir. Hesap oluştururken doğru bilgi vermeyi, şifrenizi gizli tutmayı ve hesabınızda gerçekleşen işlemlerden sorumlu olduğunuzu kabul edersiniz. Her kişi yalnızca kendi adına hesap açabilir. Yetkisiz bir kullanım fark ederseniz bizi [[email]] adresinden bilgilendirmelisiniz."),
    ("h2", "tibbi-sorumluluk-reddi", "4. Tıbbi Sorumluluk Reddi"),
    ("hl", "PulseCoach bir tıbbi cihaz, teşhis aracı veya sağlık hizmeti sağlayıcısı **değildir** ve bu amaçlarla kullanılmamalıdır. Yapay zekâ koçun antrenman, beslenme ve yaşam tarzı önerileri yalnızca genel bilgilendirme amaçlıdır; bir hekimin, diyetisyenin, fizyoterapistin veya psikoloğun tavsiyesinin, teşhisinin veya tedavisinin **yerine geçmez**. Kalori önerisi genel bir formüle dayanan bir tahmindir. Bir egzersiz veya beslenme programına başlamadan önce, özellikle mevcut bir hastalığınız, sakatlığınız, hamileliğiniz, yeme bozukluğu öykünüz veya kronik bir rahatsızlığınız varsa hekiminize danışın. Kendinizi kötü hissediyorsanız, kendinize zarar verme düşünceleriniz varsa veya acil bir durumdaysanız derhal **112**'yi arayın ya da en yakın sağlık kuruluşuna başvurun. Önerileri uygulayıp uygulamamak sizin kararınızdır."),
    ("h2", "kullanici-yukumlulukleri", "5. Kullanıcı Yükümlülükleri"),
    ("p", "Uygulamayı yalnızca hukuka uygun amaçlarla ve bu Koşullara uygun şekilde kullanacağınızı kabul edersiniz. Özellikle: Uygulamanın güvenliğini aşmaya, sistemleri aşırı yüklemeye veya otomatik araçlarla veri toplamaya çalışmamayı; yapay zekâ koçu zararlı, yasa dışı veya başkalarını hedef alan içerik üretmeye yönlendirmemeyi; başkalarına ait kişisel verileri, özellikle başka kişilerin yüzlerini içeren fotoğrafları yüklememeyi ve günlük kullanım sınırlarını aşmaya yönelik girişimlerde bulunmamayı kabul edersiniz."),
    ("h2", "icerik", "6. Kullanıcı İçeriği"),
    ("p", "Girdiğiniz kayıtlar, sohbetler ve fotoğraflar size aittir; bunları Profil > Verilerim bölümünden indirebilirsiniz. Hizmeti sunabilmemiz için bu içerikleri yalnızca Uygulamanın işleyişi kapsamında ve [[kvkk|Gizlilik ve KVKK]] metnine uygun olarak saklama ve işleme iznini bize vermiş olursunuz. İçerikleriniz yapay zekâ modellerini eğitmek, reklam veya pazarlama amacıyla kullanılmaz."),
    ("h2", "ucretlendirme", "7. Ücretlendirme"),
    ("p", "Uygulama tamamen ücretsizdir; uygulama içi satın alma veya abonelik yoktur. İleride ücretli bir özellik eklenirse bu açıkça duyurulur ve açık onayınız olmadan sizden ücret alınmaz."),
    ("h2", "fikri-mulkiyet", "8. Fikri Mülkiyet"),
    ("p", "Uygulamanın yazılımı, tasarımı, \"PulseCoach\" adı ve logosu Bora Eren Erdem'e aittir. Uygulamayı izinsiz kopyalayamaz, değiştiremez, tersine mühendislik yapamaz veya ticari amaçla dağıtamazsınız. Uygulamada kullanılan açık kaynaklı bileşenler ve veri setleri (ör. besin ve egzersiz katalogları) kendi lisanslarına tabidir."),
    ("h2", "garanti-reddi", "9. Hizmetin Sınırları, Süresi ve Garanti Reddi"),
    ("p", "PulseCoach, bireysel bir geliştirici tarafından yürütülen ve sınırlı bir süre için sunulabilecek bir projedir. Uygulama \"olduğu gibi\" ve \"mevcut olduğu ölçüde\" sunulur; kesintisiz veya hatasız çalışacağı ve yapay zekâ çıktılarının her zaman doğru olacağı garanti edilmez. Bakım veya teknik sorunlar nedeniyle Uygulama zaman zaman erişilemez olabilir. Hizmeti tamamen sonlandırmamız hâlinde bunu **en az 30 gün önceden** uygulama içinden ve kayıtlı e-posta adresinize duyurur, verilerinizi indirmeniz için süre tanır ve süre sonunda tüm kişisel verileri sileriz."),
    ("h2", "sorumluluk-sinirlamasi", "10. Sorumluluğun Sınırlandırılması"),
    ("p", "Yürürlükteki mevzuatın izin verdiği ölçüde, Uygulamanın kullanımından veya kullanılamamasından doğan dolaylı zararlardan sorumlu değiliz. Bu sınırlama, kasıt veya ağır ihmalden, kişisel verilerin hukuka aykırı işlenmesinden ya da kanunen sınırlandırılamayan hâllerden doğan sorumluluğu ortadan kaldırmaz ve tüketici olarak kanundan doğan haklarınızı etkilemez."),
    ("h2", "hesap-sonlandirma", "11. Hesabın Sonlandırılması"),
    ("p", "Hesabınızı dilediğiniz zaman Profil > Hesabımı Sil bölümünden kalıcı olarak silebilirsiniz. Bu Koşulları ağır şekilde ihlal etmeniz hâlinde hesabınızı, mümkünse önceden bildirimde bulunarak, askıya alabilir veya kapatabiliriz; bu durumda da verilerinizi indirme talebiniz karşılanır."),
    ("h2", "degisiklikler", "12. Değişiklikler"),
    ("p", "Bu Koşulları güncelleyebiliriz. Güncelleme tarihi bu sayfanın başında belirtilir; önemli değişiklikler yürürlüğe girmeden önce uygulama içinden duyurulur. Değişikliği kabul etmiyorsanız hesabınızı silerek sözleşmeyi sona erdirebilirsiniz."),
    ("h2", "app-store", "13. Apple App Store"),
    ("p", "Uygulamayı Apple App Store'dan indirdiyseniz: bu Koşullar Apple ile değil, sizinle Bora Eren Erdem arasındadır ve Uygulamadan ve içeriğinden Apple değil biz sorumluyuz. Apple'ın Uygulama için bakım veya destek yükümlülüğü yoktur. Uygulamanın herhangi bir garantiye uymaması hâlinde Apple'a bildirebilirsiniz; Apple varsa satın alma bedelini iade eder (Uygulama ücretsizdir) ve kanunun izin verdiği ölçüde başka bir garanti yükümlülüğü yoktur. Uygulamayla ilgili ürün sorumluluğu, mevzuata uygunluk, tüketici koruma ve fikri mülkiyet ihlali talepleri Apple'a değil bize yöneltilmelidir. Uygulamayı App Store Kullanım Kurallarına uygun kullanmanız gerekir. Apple ve iştirakleri bu Koşulların üçüncü taraf lehtarıdır ve bu Koşulları size karşı uygulama hakkına sahiptir."),
    ("h2", "uygulanacak-hukuk", "14. Uygulanacak Hukuk ve Uyuşmazlıklar"),
    ("p", "Bu Koşullar Türkiye Cumhuriyeti hukukuna tabidir. Uyuşmazlıklarda Türkiye Cumhuriyeti mahkemeleri ve icra daireleri yetkilidir; tüketici olarak tüketici hakem heyetlerine ve tüketici mahkemelerine başvuru hakkınız saklıdır."),
    ("h2", "iletisim", "15. İletişim"),
    ("p", "Sorularınız ve talepleriniz için [[email]] adresinden bize ulaşabilirsiniz."),
]

TERMS_EN = [
    ("p", f"Last updated: {UPDATED_EN}. These Terms of Service (\"Terms\") govern the relationship between everyone who uses PulseCoach (the \"App\") (\"User\", \"you\") and Bora Eren Erdem, who operates the App (\"we\"). How your personal data is processed is explained in the [[kvkk|Privacy & KVKK]] notice."),
    ("h2", "kabul", "1. Parties and Acceptance"),
    ("p", "PulseCoach is operated by Bora Eren Erdem, a natural person, as an individual, non-commercial project. By accepting these Terms when you create an account, or by using the App, you confirm that you have read and agree to them. If you do not agree, you must not use the App."),
    ("h2", "hizmet", "2. Description of the Service"),
    ("p", "PulseCoach is a mobile and web app that tracks workouts, nutrition, mood and body measurements and provides AI-assisted personalized recommendations based on that data. The AI coach and meal photo analysis run on open-source models hosted on our server in Turkey. AI **can make mistakes**: calories, macros, exercises and amounts estimated from photos are approximate; you should check your records and not base important decisions on these outputs alone."),
    ("h2", "uygunluk", "3. Eligibility and Your Account"),
    ("p", "You must be **at least 18 years old** to use the App. When creating an account you agree to provide accurate information, keep your password confidential and be responsible for activity under your account. Each person may only create an account for themselves. If you notice unauthorized use, notify us at [[email]]."),
    ("h2", "tibbi-sorumluluk-reddi", "4. Medical Disclaimer"),
    ("hl", "PulseCoach is **not** a medical device, a diagnostic tool or a healthcare provider and must not be used for these purposes. The AI coach's workout, nutrition and lifestyle recommendations are for general information only and do **not** replace the advice, diagnosis or treatment of a physician, dietitian, physical therapist or psychologist. The calorie suggestion is an estimate based on a general formula. Before starting an exercise or nutrition program, consult your physician, especially if you have an existing condition, injury, pregnancy, a history of eating disorders or a chronic illness. If you feel unwell, have thoughts of harming yourself or are in an emergency, call your local emergency number (**112** in Turkey) immediately or go to the nearest medical facility. Whether you follow the recommendations is your decision."),
    ("h2", "kullanici-yukumlulukleri", "5. User Obligations"),
    ("p", "You agree to use the App only for lawful purposes and in line with these Terms. In particular, you agree not to try to breach the App's security, overload its systems or scrape data with automated tools; not to steer the AI coach into producing harmful, unlawful or targeted content; not to upload other people's personal data, especially photos showing other people's faces; and not to try to circumvent daily usage limits."),
    ("h2", "icerik", "6. Your Content"),
    ("p", "The logs, chats and photos you enter belong to you; you can download them from Profile > My Data. So that we can provide the service, you allow us to store and process this content only for the App's operation and in line with the [[kvkk|Privacy & KVKK]] notice. Your content is not used to train AI models or for advertising or marketing."),
    ("h2", "ucretlendirme", "7. Pricing"),
    ("p", "The App is entirely free; there are no in-app purchases or subscriptions. If a paid feature is added in the future, it will be clearly announced and you will not be charged without your explicit approval."),
    ("h2", "fikri-mulkiyet", "8. Intellectual Property"),
    ("p", "The App's software, design, the \"PulseCoach\" name and logo belong to Bora Eren Erdem. You may not copy, modify, reverse-engineer or commercially distribute the App without permission. Open-source components and datasets used in the App (e.g. food and exercise catalogs) are subject to their own licenses."),
    ("h2", "garanti-reddi", "9. Service Limitations, Duration and Disclaimer"),
    ("p", "PulseCoach is a project run by an individual developer and may be offered for a limited time. The App is provided \"as is\" and \"as available\"; we do not guarantee that it will be uninterrupted or error-free or that AI outputs will always be accurate. The App may occasionally be unavailable due to maintenance or technical issues. If we discontinue the service entirely, we will announce it **at least 30 days in advance** in the app and to your registered email address, give you time to download your data, and delete all personal data at the end of that period."),
    ("h2", "sorumluluk-sinirlamasi", "10. Limitation of Liability"),
    ("p", "To the extent permitted by applicable law, we are not liable for indirect damages arising from your use of or inability to use the App. This limitation does not exclude liability for intent or gross negligence, for unlawful processing of personal data or in cases where liability cannot be limited by law, and it does not affect your statutory rights as a consumer."),
    ("h2", "hesap-sonlandirma", "11. Account Termination"),
    ("p", "You can permanently delete your account at any time from Profile > Delete My Account. If you seriously violate these Terms, we may suspend or close your account, with prior notice where possible; even then, your request to download your data will be honored."),
    ("h2", "degisiklikler", "12. Changes"),
    ("p", "We may update these Terms. The update date is shown at the top of this page; material changes are announced in the app before they take effect. If you do not accept a change, you can end the agreement by deleting your account."),
    ("h2", "app-store", "13. Apple App Store"),
    ("p", "If you downloaded the App from the Apple App Store: these Terms are between you and Bora Eren Erdem, not Apple, and we, not Apple, are responsible for the App and its content. Apple has no obligation to provide maintenance or support for the App. If the App fails to conform to any warranty, you may notify Apple, and Apple will refund the purchase price, if any (the App is free); to the extent permitted by law, Apple has no other warranty obligation. Product liability, regulatory compliance, consumer protection and intellectual property claims relating to the App must be directed to us, not Apple. You must use the App in compliance with the App Store usage rules. Apple and its subsidiaries are third-party beneficiaries of these Terms and may enforce them against you."),
    ("h2", "uygulanacak-hukuk", "14. Governing Law and Disputes"),
    ("p", "These Terms are governed by the laws of the Republic of Turkey. The courts and enforcement offices of the Republic of Turkey have jurisdiction over disputes; your right as a consumer to apply to consumer arbitration committees and consumer courts is reserved."),
    ("h2", "iletisim", "15. Contact"),
    ("p", "You can reach us with questions and requests at [[email]]."),
]
