"""Salonda yaygın egzersiz adlarının katalogdaki standart kayda sabit eşlemesi.

food_aliases.py ile aynı mekanizma (bkz. BilingualCatalog aliases): 2026-09-27
canlı testte "latpulldown" -> "Tek Kollu Lat Aşağı Çekiş" (tek kollu varyant)
kaydedildi; kullanıcının geçmişi "Geniş Tutuş Lat Aşağı Çekme" olduğu için
rekor/ilerleme karşılaştırması da yanlış harekete bağlandı. Benzer şekilde
"biceps curl" -> "Eğimli İç Pazı Curl'ü", "lat pull down" -> "Temiz Çekiş",
"chest fly" -> "Koşu Serbest Bırakmalı Göğüs İtme", "leg curl" -> "Topla
Bacak Kıvırma", "row" -> "Kızak Kürek Çekme" gidiyordu. Genel fuzzy
algoritmaya dokunulmadı; yalnız bu TAM sorgular için geçerli.

2026-09-28 (canlı push antrenmanı + 150 sorguluk tarama): "skull crusher" ->
bantlı varyant, "cable pushdown" -> eğimli varyant, "kablo crossover" -> "Kablo
Mekik", "kürek makinesi" -> smith kürek, "french press" -> "Press Sit-Up".
Aynı hareketin farklı yazımları TEK kayda gider (ör. makine göğüs presi için
"chest press", "göğüs pres", "chest press makinesi") - geçmiş ve rekor aynı
satırda birikir.

Anahtar: exercise_catalog_service.normalize_query'den geçmiş sorgu (tr_lower +
tek boşluk; "dumbell" -> "dumbbell", "skull crusher" -> "skullcrusher", "push
down" -> "pushdown"). Değer: katalogdaki name_tr (benzersiz; test_exercise_aliases
hepsinin katalogda olduğunu denetler).
"""

_WIDE_LAT = "Geniş Tutuş Lat Aşağı Çekme"
_DB_CURL = "Dambıl Pazı Kıvırma"
_BENCH = "Barbell Bench Press"
_INCLINE_BENCH = "Eğimli Barbell Bench Press"
_DB_BENCH = "Dambıl Sehpada Göğüs Presi"
_INCLINE_DB = "Eğimli Dumbbell Presi"
_MACHINE_CHEST = "Makinede Göğüs Presi"
_MACHINE_SHOULDER = "Makinede Omuz Presi"
_CABLE_FLY = "Kablo Çaprazlama"
_PEC_DECK = "Peck Deck Makinesi"
_SKULL = "EZ Bar Kafatası Ezici (Skullcrusher)"
_PUSHDOWN = "Triceps Aşağı İtme"
_ROPE_PUSHDOWN = "Halat Bağlantılı Triceps Aşağı İtme"
_DB_ROW = "Tek Kol Dumbbell Kürek Çekme"
_CABLE_ROW = "Oturarak Kablo Kürek Çekme"
_SQUAT = "Squat (Çömelme)"
_TREADMILL_RUN = "Koşu Bandında Koşma"

EXERCISE_ALIASES: dict[str, str] = {
    # Göğüs
    "bench press": _BENCH,
    "bench": _BENCH,
    "flat bench": _BENCH,
    "flat bench press": _BENCH,
    "düz bench": _BENCH,
    "düz bench press": _BENCH,
    "barbell bench": _BENCH,
    "göğüs bench press": _BENCH,
    "incline bench press": _INCLINE_BENCH,
    "incline bench": _INCLINE_BENCH,
    "incline barbell bench press": _INCLINE_BENCH,
    "incline barbell press": _INCLINE_BENCH,
    "eğimli bench press": _INCLINE_BENCH,
    "eğimli bench": _INCLINE_BENCH,
    "dumbbell bench press": _DB_BENCH,
    "dumbbell press": _DB_BENCH,
    "dumbbell chest press": _DB_BENCH,
    "dumbbell göğüs presi": _DB_BENCH,
    "dumbbell göğüs press": _DB_BENCH,
    "flat dumbbell press": _DB_BENCH,
    "dambıl bench press": _DB_BENCH,
    "dambıl press": _DB_BENCH,
    "dambıl chest press": _DB_BENCH,
    "dambıl göğüs press": _DB_BENCH,
    "dambıl göğüs presi": _DB_BENCH,
    "düz dambıl press": _DB_BENCH,
    "incline dumbbell press": _INCLINE_DB,
    "incline dumbbell bench press": _INCLINE_DB,
    "incline dumbbell chest press": _INCLINE_DB,
    "dumbbell incline press": _INCLINE_DB,
    "incline dambıl press": _INCLINE_DB,
    "eğimli dambıl press": _INCLINE_DB,
    "eğimli dambıl presi": _INCLINE_DB,
    "eğimli dumbbell press": _INCLINE_DB,
    "eğimli dambıl göğüs presi": _INCLINE_DB,  # -> çekiç tutuş varyantı
    "eğimli dambıl göğüs press": _INCLINE_DB,
    "incline dambıl göğüs presi": _INCLINE_DB,
    "chest press": _MACHINE_CHEST,
    "machine chest press": _MACHINE_CHEST,
    "chest press machine": _MACHINE_CHEST,
    "chest press makinesi": _MACHINE_CHEST,
    "makinede chest press": _MACHINE_CHEST,
    "makine chest press": _MACHINE_CHEST,  # "chest press (makine)"
    "göğüs pres": _MACHINE_CHEST,
    "göğüs press": _MACHINE_CHEST,
    "göğüs presi": _MACHINE_CHEST,
    "göğüs pres makinesi": _MACHINE_CHEST,
    "göğüs press makinesi": _MACHINE_CHEST,
    "makinede göğüs press": _MACHINE_CHEST,
    "makine göğüs presi": _MACHINE_CHEST,
    "incline chest press makinesi": "Kaldıraç Eğimli Göğüs Presi",
    "incline chest press machine": "Kaldıraç Eğimli Göğüs Presi",
    "makinede incline chest press": "Kaldıraç Eğimli Göğüs Presi",
    "incline machine press": "Kaldıraç Eğimli Göğüs Presi",
    "smith incline press": "Smith Makinesi Eğimli Göğüs Presi",
    "smith incline bench press": "Smith Makinesi Eğimli Göğüs Presi",
    "smith incline chest press": "Smith Makinesi Eğimli Göğüs Presi",
    "smith machine incline chest press": "Smith Makinesi Eğimli Göğüs Presi",
    "decline bench press": "Decline Barbell Bench Press",
    "decline bench": "Decline Barbell Bench Press",
    "decline barbell press": "Decline Barbell Bench Press",
    "decline press": "Decline Barbell Bench Press",
    "close grip bench press": "Kapalı Tutuş Barbell Bench Press",
    "dar tutuş bench press": "Kapalı Tutuş Barbell Bench Press",
    "dar tutuş bench": "Kapalı Tutuş Barbell Bench Press",
    "cable fly": _CABLE_FLY,
    "cable flye": _CABLE_FLY,
    "cable chest fly": _CABLE_FLY,
    "cable crossover fly": _CABLE_FLY,
    "crossover": _CABLE_FLY,
    "kablo fly": _CABLE_FLY,
    "kablo crossover": _CABLE_FLY,
    "kablo çaprazlama": _CABLE_FLY,
    "kablo çapraz": _CABLE_FLY,
    "çapraz kablo": _CABLE_FLY,
    "machine fly": _PEC_DECK,
    "makine fly": _PEC_DECK,
    "fly makinesi": _PEC_DECK,
    "chest fly makinesi": _PEC_DECK,
    "pec fly": _PEC_DECK,
    "butterfly makinesi": _PEC_DECK,
    "kelebek makinesi": _PEC_DECK,
    "chest fly": "Dambıl Kanat Açma (Flyes)",
    "dumbbell fly": "Dambıl Kanat Açma (Flyes)",
    # Omuz
    "machine shoulder press": _MACHINE_SHOULDER,
    "shoulder press machine": _MACHINE_SHOULDER,
    "shoulder press makinesi": _MACHINE_SHOULDER,
    "makinede shoulder press": _MACHINE_SHOULDER,
    "makine shoulder press": _MACHINE_SHOULDER,
    "omuz press makinesi": _MACHINE_SHOULDER,
    "omuz pres makinesi": _MACHINE_SHOULDER,
    "omuz presi makinesi": _MACHINE_SHOULDER,
    "makinede omuz press": _MACHINE_SHOULDER,
    "makinede omuz pres": _MACHINE_SHOULDER,
    "overhead press": "Ayakta Asker Presi (Military Press)",
    "dumbbell shoulder press": "Dambıl Omuz Presi",
    "dambıl shoulder press": "Dambıl Omuz Presi",
    "dambıl omuz press": "Dambıl Omuz Presi",
    "yan kaldırma": "Yanal Kaldırma",
    "dambıl lateral raise": "Dambıl Yanal Kaldırma",
    "dambıl yan kaldırma": "Dambıl Yanal Kaldırma",
    "cable lateral raise": "Ayakta Kablo Yan Kaldırma",
    "kablo lateral raise": "Ayakta Kablo Yan Kaldırma",
    "kablo yan kaldırma": "Ayakta Kablo Yan Kaldırma",
    "kablo yana açış": "Ayakta Kablo Yan Kaldırma",
    "reverse pec deck": "Arka Omuz Peck Deck Makinesi",
    "ters peck deck": "Arka Omuz Peck Deck Makinesi",
    "rear delt machine": "Arka Omuz Peck Deck Makinesi",
    "arka omuz makinesi": "Arka Omuz Peck Deck Makinesi",
    "reverse fly": "Ters Flyes (Kanat Açma)",
    "arka omuz fly": "Ters Flyes (Kanat Açma)",
    "upright row": "Barbell Dik Çekiş (Upright Row)",
    "barbell upright row": "Barbell Dik Çekiş (Upright Row)",
    "dik çekiş": "Barbell Dik Çekiş (Upright Row)",
    "shrug": "Barbell Omuz Silkme (Shrug)",
    "barbell shrug": "Barbell Omuz Silkme (Shrug)",
    "omuz silkme": "Barbell Omuz Silkme (Shrug)",
    "dambıl shrug": "Dambıl Omuz Silkme (Shrug)",
    "dambıl omuz silkme": "Dambıl Omuz Silkme (Shrug)",
    # Arka kol (triceps)
    "skullcrusher": _SKULL,
    "barbell skullcrusher": _SKULL,
    "triceps skullcrusher": _SKULL,
    "tricep skullcrusher": _SKULL,
    "ez skullcrusher": _SKULL,
    "ez bar skullcrusher": _SKULL,
    "kafatası ezici": _SKULL,
    "french press": _SKULL,
    "fransız press": _SKULL,
    "fransız presi": _SKULL,
    "lying triceps extension": _SKULL,
    "yatarak triceps extension": _SKULL,
    "ez bar triceps extension": _SKULL,
    "dumbbell skullcrusher": "Yatarak Dumbbell Triceps Uzatması",
    "dambıl skullcrusher": "Yatarak Dumbbell Triceps Uzatması",
    "pushdown": _PUSHDOWN,
    "triceps pushdown": _PUSHDOWN,
    "tricep pushdown": _PUSHDOWN,
    "triceps cable pushdown": _PUSHDOWN,
    "cable pushdown": _PUSHDOWN,
    "cable triceps pushdown": _PUSHDOWN,
    "cable tricep pushdown": _PUSHDOWN,
    "kablo pushdown": _PUSHDOWN,
    "kablo triceps pushdown": _PUSHDOWN,
    "kablo triceps": _PUSHDOWN,
    "bar pushdown": _PUSHDOWN,
    "düz bar pushdown": _PUSHDOWN,
    "straight bar pushdown": _PUSHDOWN,
    "rope pushdown": _ROPE_PUSHDOWN,
    "rope triceps pushdown": _ROPE_PUSHDOWN,
    "rope tricep pushdown": _ROPE_PUSHDOWN,
    "triceps rope pushdown": _ROPE_PUSHDOWN,
    "halat pushdown": _ROPE_PUSHDOWN,
    "halatla pushdown": _ROPE_PUSHDOWN,
    "halat triceps pushdown": _ROPE_PUSHDOWN,
    "ip pushdown": _ROPE_PUSHDOWN,
    "v bar pushdown": "V Bar Bağlantılı Triceps Aşağı İtme",
    "reverse grip pushdown": "Ters Tutuş Triceps İndirme",
    "ters tutuş pushdown": "Ters Tutuş Triceps İndirme",
    "overhead triceps extension": "Ayakta Dumbbell Triceps Uzatma",
    "dumbbell overhead triceps extension": "Ayakta Dumbbell Triceps Uzatma",
    "overhead extension": "Ayakta Dumbbell Triceps Uzatma",
    "baş üstü triceps uzatma": "Ayakta Dumbbell Triceps Uzatma",
    "cable overhead triceps extension": "Kablo Halat Üstten Triceps Uzatması",
    "cable overhead extension": "Kablo Halat Üstten Triceps Uzatması",
    "rope overhead extension": "Kablo Halat Üstten Triceps Uzatması",
    "halat overhead extension": "Kablo Halat Üstten Triceps Uzatması",
    "kablo overhead extension": "Kablo Halat Üstten Triceps Uzatması",
    "kickback": "Triceps Dumbbell Geri Uzatma",
    "triceps kickback": "Triceps Dumbbell Geri Uzatma",
    "tricep kickback": "Triceps Dumbbell Geri Uzatma",
    "dumbbell kickback": "Triceps Dumbbell Geri Uzatma",
    "dambıl kickback": "Triceps Dumbbell Geri Uzatma",
    # Ön kol (biceps)
    "biceps curl": _DB_CURL,
    "bicep curl": _DB_CURL,
    "pazı curl": _DB_CURL,
    "dumbbell curl": _DB_CURL,
    "dambıl curl": _DB_CURL,
    "cable curl": "Ayakta Biceps Kablo Kıvırma",
    "cable biceps curl": "Ayakta Biceps Kablo Kıvırma",
    "kablo curl": "Ayakta Biceps Kablo Kıvırma",
    "kablo biceps curl": "Ayakta Biceps Kablo Kıvırma",
    "kablo pazı curl": "Ayakta Biceps Kablo Kıvırma",
    # Sırt
    "lat pulldown": _WIDE_LAT,
    "latpulldown": _WIDE_LAT,
    "lat çekiş": _WIDE_LAT,
    "lat çekme": _WIDE_LAT,
    "lat pulldown makinesi": _WIDE_LAT,
    "dar tutuş lat pulldown": "Kapalı Tutuş Ön Lat Pulldown",
    "straight arm pulldown": "Düz Kol Çekiş (Pulldown)",
    "düz kol pulldown": "Düz Kol Çekiş (Pulldown)",
    "rope pulldown": "Düz Kol Çekiş (Pulldown)",
    "row": _CABLE_ROW,
    "seated row": _CABLE_ROW,
    "oturarak row": _CABLE_ROW,
    "kablo row": _CABLE_ROW,
    "cable row": _CABLE_ROW,
    "kablo kürek": _CABLE_ROW,
    "kablo kürek çekme": _CABLE_ROW,
    "dumbbell row": _DB_ROW,
    "one arm dumbbell row": _DB_ROW,
    "tek kol dumbbell row": _DB_ROW,
    "tek kol dambıl row": _DB_ROW,
    "tek kol row": _DB_ROW,
    "dambıl row": _DB_ROW,
    "dambıl kürek": _DB_ROW,
    "dambıl kürek çekme": _DB_ROW,
    "tek kol dambıl kürek": _DB_ROW,
    "tek kol dambıl kürek çekme": _DB_ROW,
    "machine row": "Kaldıraç Kürek Çekme (Iso Row)",
    "row makinesi": "Kaldıraç Kürek Çekme (Iso Row)",
    "makinede row": "Kaldıraç Kürek Çekme (Iso Row)",
    "makinede kürek": "Kaldıraç Kürek Çekme (Iso Row)",
    "seated row machine": "Kaldıraç Kürek Çekme (Iso Row)",
    "chest supported row": "Kaldıraç Kürek Çekme (Iso Row)",
    "barbell row": "Eğilerek Barbell Kürek Çekme",
    "bent over row": "Eğilerek Barbell Kürek Çekme",
    "eğilerek row": "Eğilerek Barbell Kürek Çekme",
    "barbell kürek": "Eğilerek Barbell Kürek Çekme",
    "t bar row": "Tutacaklı T-Bar Kürek Çekme",
    "t-bar row": "Tutacaklı T-Bar Kürek Çekme",
    "pullover": "Bükülmüş Kol Dumbbell Pullover",
    "dumbbell pullover": "Bükülmüş Kol Dumbbell Pullover",
    "dambıl pullover": "Bükülmüş Kol Dumbbell Pullover",
    "back extension": "Hiperekstansiyonlar (Sırt Uzatması)",
    "sırt uzatma": "Hiperekstansiyonlar (Sırt Uzatması)",
    "stiff leg deadlift": "Dik Dizli Barbell Deadlift",
    # Bacak / kalça
    "back squat": _SQUAT,
    "bulgarian split squat": "Bulgarian Split Squat (Bulgar Squat)",
    "bulgarian squat": "Bulgarian Split Squat (Bulgar Squat)",
    "bulgar squat": "Bulgarian Split Squat (Bulgar Squat)",
    "bulgar split squat": "Bulgarian Split Squat (Bulgar Squat)",
    "leg curl": "Yatarak Bacak Kıvırma (Curl)",
    "calf raise": "Ayakta Baldır Kaldırmaları",
    "leg press calf raise": "Bacak Pres Makinesinde Baldır Presi",
    "lunge": "Dambıl Hamle (Lunge)",
    "hamle": "Dambıl Hamle (Lunge)",
    "step up": "Dambıl Adım Yükselişi (Step Up)",
    "glute bridge": "Kalça Kaldırma (Köprü Kurma)",
    "kalça köprüsü": "Kalça Kaldırma (Köprü Kurma)",
    "hip abduction": "Uyluk Abduktörü",
    "hip abduction machine": "Uyluk Abduktörü",
    "abductor": "Uyluk Abduktörü",
    "abductor makinesi": "Uyluk Abduktörü",
    "abduction makinesi": "Uyluk Abduktörü",
    "dış bacak makinesi": "Uyluk Abduktörü",
    "hip adduction": "Uyluk Adduktörü",
    "hip adduction machine": "Uyluk Adduktörü",
    "adductor": "Uyluk Adduktörü",
    "adductor makinesi": "Uyluk Adduktörü",
    "iç bacak makinesi": "Uyluk Adduktörü",
    "kettlebell swing": "Kettlebell Swing (Çift Kol)",
    "kb swing": "Kettlebell Swing (Çift Kol)",
    "swing": "Kettlebell Swing (Çift Kol)",
    "wall sit": "Duvarda Oturma (Wall Sit)",
    "duvarda oturma": "Duvarda Oturma (Wall Sit)",
    "jumping jack": "Jumping Jack (Açılıp Kapanma Zıplaması)",
    "jumping jacks": "Jumping Jack (Açılıp Kapanma Zıplaması)",
    # Karın
    "crunch": "Crunch (Yarım Mekik)",
    "crunches": "Crunch (Yarım Mekik)",
    "leg raise": "Düz Sehpada Yatarak Bacak Kaldırma",
    "lying leg raise": "Düz Sehpada Yatarak Bacak Kaldırma",
    "yatarak bacak kaldırma": "Düz Sehpada Yatarak Bacak Kaldırma",
    "ab wheel": "Ab Roller (veya Karın Rulosu)",
    "karın tekerleği": "Ab Roller (veya Karın Rulosu)",
    "side plank": "Yan Köprü (Side Bridge)",
    "yan plank": "Yan Köprü (Side Bridge)",
    # Kardiyo (match_for_set yalnız 'kardiyo' kategorisine bağlar)
    "koşu bandı": _TREADMILL_RUN,
    "treadmill": _TREADMILL_RUN,
    "koşu bandında koşu": _TREADMILL_RUN,
    "treadmill koşu": _TREADMILL_RUN,
    "koşu bandında yürüyüş": "Yürüyüş, Koşu Bandı",
    "treadmill yürüyüş": "Yürüyüş, Koşu Bandı",
    "eğimli yürüyüş": "Yürüyüş, Koşu Bandı",
    "incline walk": "Yürüyüş, Koşu Bandı",
    "kürek makinesi": "Kürek Makinesi (Ergometre)",
    "rowing machine": "Kürek Makinesi (Ergometre)",
    "rowing": "Kürek Makinesi (Ergometre)",
    "kürek ergometresi": "Kürek Makinesi (Ergometre)",
    "sabit bisiklet": "Sabit Bisiklet Sürme",
    "kondisyon bisikleti": "Sabit Bisiklet Sürme",
    "spinning": "Sabit Bisiklet Sürme",
    "stairmaster": "Merdiven Makinesi (Stairmaster)",
    "merdiven makinesi": "Merdiven Makinesi (Stairmaster)",
    "step makinesi": "Merdiven Makinesi (Stairmaster)",
    "stepper": "Merdiven Makinesi (Stairmaster)",
    # 2026-09-29: modelin standart İngilizce adlandırması (bkz. exercise_resolver) -
    # kullanıcının farklı Türkçe/argo ifadeleri bu adlara çevrilir, eş-ad tek yerde.
    "stair climber": "Merdiven Makinesi (Stairmaster)",
    "stair stepper": "Merdiven Makinesi (Stairmaster)",
    "chest fly machine": _PEC_DECK,
    "machine chest fly": _PEC_DECK,
    "woodchopper": "Ayakta Kablo Odun Kesme (Wood Chop)",
    "cable woodchopper": "Ayakta Kablo Odun Kesme (Wood Chop)",
    "wood chop": "Ayakta Kablo Odun Kesme (Wood Chop)",
    "diamond push-up": "Triceps Odaklı Şınav (Yakın Tutuş)",
    "diamond push up": "Triceps Odaklı Şınav (Yakın Tutuş)",
    "close grip push-up": "Triceps Odaklı Şınav (Yakın Tutuş)",
    "nordic curl": "Doğal Kalça Hamstring Kaldırma",
    "nordic hamstring curl": "Doğal Kalça Hamstring Kaldırma",
    "calf raise machine": "Ayakta Baldır Kaldırmaları",
    "standing calf raise machine": "Ayakta Baldır Kaldırmaları",
    "seated calf raise machine": "Oturarak Baldır Kaldırma",
    "oblique crunch": "Yan Karın Mekikleri",
    "side crunch": "Yan Karın Mekikleri",
    "hamstring curl": "Yatarak Bacak Kıvırma (Curl)",
    "hamstring curl machine": "Yatarak Bacak Kıvırma (Curl)",
    "farmer's carry": "Çiftçi Yürüyüşü",
    "farmers carry": "Çiftçi Yürüyüşü",
    "farmer carry": "Çiftçi Yürüyüşü",
    "machine rear delt fly": "Arka Omuz Peck Deck Makinesi",
    "rear delt fly machine": "Arka Omuz Peck Deck Makinesi",
}
